Network Rerouter Daemon (nerd): IPQ::IpqUdpPacket Class Reference
IPQ::IpqUdpPacket Class Reference
An complete IPv4/UDP packet that was received via IpqSocket.
#include <IPQ.hpp>
Public Member Functions
in_port_t getUdpSource () const
Retrieve the UDP source port of a packet.
in_port_t getUdpDest () const
Retrieve the UDP destination port of a packet.
struct udphdr & getUdpHeader () const
Retrieve the complete UDP header of a packet.
struct udphdr & getUdpHeader ()
Retrieve the complete UDP header of a packet.
const boost::uint8_t * getUdpPayload (std::size_t &size) const
Retrive the UDP payload of a packet.
boost::uint8_t * getUdpPayload (std::size_t &size)
Retrive the UDP payload of a packet.
virtual void print (std::ostream &out) const
Print a TCP packet to stdout in an easy-to-read format.
virtual ~IpqUdpPacket ()
Destructor for IpqUdpPacket.
in_addr_t getIpSource () const
Retrieve the source IP address of a packet.
in_addr_t getIpDest () const
Retrieve the destination IP address of a packet.
boost::uint8_t getProtocol () const
Retrieve the encapsulated protocol number of a packet.
boost::uint16_t getId () const
Retrieve the IP ID of a packet.
boost::uint16_t getFragOffset () const
Retrieve the fragment offset of a packet, in bytes.
bool getMoreFrags () const
Retrieve the "more fragments to follow" flag of a packet.
struct iphdr & getIpHeader () const
Retrieve the complete IP header of a packet.
struct iphdr & getIpHeader ()
Retrieve the complete IP header of a packet.
const boost::uint8_t * getIpPayload (std::size_t &size) const
Retrive the IP payload of a packet.
boost::uint8_t * getIpPayload (std::size_t &size)
Retrive the IP payload of a packet.
unsigned long getNfId () const
Retrieve the Netfilter ID of a packet.
unsigned long getNfMark () const
Retrieve the Netfilter mark value of a packet.
void getTimestamp (struct timeval &time) const
Retrieve the arrival time of a packet.
unsigned getNfHook () const
Retrieve the number of the Netfilter hook on which the packet arrived.
const char(& getIndevName () const)[IFNAMSIZ]
Retrieve the name of the interface on which the packet arrived, if available.
const char(& getOutdevName () const)[IFNAMSIZ]
Retrieve the name of the interface on which the packet will leave, if available.
unsigned short getHwProtocol () const
Retrieve the hardware protocol number of the packet.
unsigned short getHwType () const
Retrieve the hardware type on which the packet arrived.
const unsigned char(& getHwSource (unsigned short &addrlen) const)[8]
Retrieve the source hardware address of the packet.
const boost::uint8_t * getPacket (std::size_t &size) const
Retrieve the packet.
boost::uint8_t * getPacket (std::size_t &size)
Retrieve the packet.
Protected Member Functions
IpqUdpPacket (LibWheel::auto_array< boost::uint8_t > buf, std::size_t buflen)
Constructor for IpqTcpPacket.
struct udphdr & doGetUdpHeader () const
Retrieve the complete UDP header of a packet.
boost::uint8_t * doGetUdpPayload (std::size_t &size) const
Retrive the UDP payload of a packet.
virtual void updateChecksums ()
Update the checksums on an UDP packet.
struct iphdr & doGetIpHeader () const
Retrieve the complete IP header of a packet.
boost::uint8_t * doGetIpPayload (std::size_t &size) const
Retrive the IP payload of a packet.
boost::uint8_t * doGetPacket (std::size_t &size) const
Retrieve the packet.
Static Protected Member Functions
static IpqPacket * createPacket (LibWheel::auto_array< boost::uint8_t > buf, std::size_t buflen)
Create an IpqPacket or one of its subclasses from a libipq packet message.
Protected Attributes
LibWheel::auto_array
< boost::uint8_t > packet
The packet message received from kernelspace.
std::size_t packetLen
the length of the packet message in IpqPacket::packet, in bytes.
bool dirty
true if the packet has been modified but checksums have not been updated; false otherwise.
Friends
IpqPacket * IpqPacket::createPacket (LibWheel::auto_array< boost::uint8_t >, std::size_t)
Allow IpqSocket::createPacket() to access the contstructor.
Detailed Description
An complete IPv4/UDP packet that was received via IpqSocket.
Contains UDP header fields and the UDP payload.
Constructor & Destructor Documentation
IPQ::IpqUdpPacket::~IpqUdpPacket () [virtual]
Destructor for IpqUdpPacket.
Definition at line 1314 of file IPQ.cpp.
IPQ::IpqUdpPacket::IpqUdpPacket (LibWheel::auto_array< boost::uint8_t > buf, std::size_t buflen) [protected]
Constructor for IpqTcpPacket.
Initializes an IpqTcpPacket from a libipq packet message.
Definition at line 1322 of file IPQ.cpp.
Member Function Documentation
IpqPacket * IPQ::IpqPacket::createPacket (LibWheel::auto_array< boost::uint8_t > buf, std::size_t buflen) [static, protected, inherited]
Create an IpqPacket or one of its subclasses from a libipq packet message.
A packet will be deemed to be an IPv4 packet if it has a full IPv4 header and the data length indicated by the header matches the packet's length. A packet will be deemed to be a TCP or UDP packet if it is an IPv4 packet and it has a full TCP or UDP header.
Returns:
A pointer to a dynamically-allocated IpqPacket, or one of its subclasses. This pointer must be freed using delete, and a verdict should be set on it using IpqSocket::sendResponse().
Definition at line 731 of file IPQ.cpp.
References LibWheel::auto_array::get(), and IPQ::IpqPacket::IpqPacket().
Referenced by IPQ::IpqSocket::recvPacket().
struct iphdr & IPQ::IpqIpPacket::doGetIpHeader () const [read, protected, inherited]
Retrieve the complete IP header of a packet.
A reference to the packet's IP header.
Definition at line 928 of file IPQ.cpp.
References IPQ::IpqPacket::packet, and LibWheel::auto_array::get().
Referenced by IPQ::IpqIpPacket::getIpHeader().
boost::uint8_t * IPQ::IpqIpPacket::doGetIpPayload (std::size_t & size) const [protected, inherited]
Retrive the IP payload of a packet.
Parameters:
[out] size A reference to a location to store the packet's IP payload size, in bytes..
Returns:
A const pointer to the packet's IP payload.
Definition at line 941 of file IPQ.cpp.
References IPQ::IpqPacket::packet, and LibWheel::auto_array::get().
Referenced by IPQ::IpqIpPacket::getIpPayload().
boost::uint8_t * IPQ::IpqPacket::doGetPacket (std::size_t & size) const [protected, inherited]
Retrieve the packet.
It will only be available if the copy mode on the libipq handle used to receive it was IpqSocket::PACKET and the copy range was greater than zero.
Parameters:
[out] size A reference to a location to write the length of the payload, in bytes.
Returns:
A pointer to the packet.
Definition at line 703 of file IPQ.cpp.
References IPQ::IpqPacket::packet, and LibWheel::auto_array::get().
Referenced by IPQ::IpqPacket::getPacket().
struct udphdr & IPQ::IpqUdpPacket::doGetUdpHeader () const [read, protected]
Retrieve the complete UDP header of a packet.
A reference to the packet's UDP header.
Definition at line 1332 of file IPQ.cpp.
References IPQ::IpqPacket::packet, and LibWheel::auto_array::get().
Referenced by getUdpHeader().
boost::uint8_t * IPQ::IpqUdpPacket::doGetUdpPayload (std::size_t & size) const [protected]
Retrive the UDP payload of a packet.
Parameters:
[out] size A reference to a location to store the packet's UDP payload size, in bytes..
Returns:
A pointer to the packet's UDP payload.
Definition at line 1346 of file IPQ.cpp.
References IPQ::IpqPacket::packet, and LibWheel::auto_array::get().
Referenced by getUdpPayload().
boost::uint16_t IPQ::IpqIpPacket::getFragOffset () const [inherited]
Retrieve the fragment offset of a packet, in bytes.
If not zero, then this is a non-leading fragment.
Returns:
The packet's fragment offset.
Definition at line 817 of file IPQ.cpp.
References IPQ::IpqIpPacket::getIpHeader().
Referenced by IPQ::IpqIpPacket::print(), and NERD::ConnectionServer::handlePacket().
unsigned short IPQ::IpqPacket::getHwProtocol () const [inherited]
Retrieve the hardware protocol number of the packet.
Returns:
The packet's hardware protocol number.
Definition at line 585 of file IPQ.cpp.
References IPQ::IpqPacket::packet, and LibWheel::auto_array::get().
Referenced by IPQ::IpqPacket::print().
const unsigned char(& IPQ::IpqPacket::getHwSource (unsigned short & addrlen))[8] [inherited]
Retrieve the source hardware address of the packet.
Parameters:
[out] addrlen A reference to a location to write the actual length of the address, in bytes.
Returns:
A reference to the packet's source hardware address.
Definition at line 608 of file IPQ.cpp.
Referenced by IPQ::IpqPacket::print().
unsigned short IPQ::IpqPacket::getHwType () const [inherited]
Retrieve the hardware type on which the packet arrived.
Returns:
The packet's arrival hardware type.
Definition at line 596 of file IPQ.cpp.
References IPQ::IpqPacket::packet, and LibWheel::auto_array::get().
Referenced by IPQ::IpqPacket::print().
boost::uint16_t IPQ::IpqIpPacket::getId () const [inherited]
Retrieve the IP ID of a packet.
Returns:
The packet's IPID.
Definition at line 805 of file IPQ.cpp.
References IPQ::IpqIpPacket::getIpHeader().
Referenced by IPQ::IpqIpPacket::print().
const char(& IPQ::IpqPacket::getIndevName ())[IFNAMSIZ] [inherited]
Retrieve the name of the interface on which the packet arrived, if available.
Returns:
A reference to the packet's arrival interface name.
Definition at line 563 of file IPQ.cpp.
Referenced by IPQ::IpqPacket::print().
in_addr_t IPQ::IpqIpPacket::getIpDest () const [inherited]
Retrieve the destination IP address of a packet.
Returns:
The packet's destination IP address.
Definition at line 783 of file IPQ.cpp.
References IPQ::IpqIpPacket::getIpHeader().
Referenced by IPQ::IpqSocket::sendResponse(), IPQ::IpqIpPacket::print(), NERD::ConnectionServer::handlePacket(), and NERD::ConnectionServer::createConnection().
struct iphdr & IPQ::IpqIpPacket::getIpHeader () const [read, inherited]
Retrieve the complete IP header of a packet.
A const reference to the packet's IP header.
Definition at line 840 of file IPQ.cpp.
References IPQ::IpqIpPacket::doGetIpHeader().
Referenced by IPQ::IpqIpPacket::getIpSource(), IPQ::IpqIpPacket::getIpDest(), IPQ::IpqIpPacket::getProtocol(), IPQ::IpqIpPacket::getId(), IPQ::IpqIpPacket::getFragOffset(), IPQ::IpqIpPacket::getMoreFrags(), IPQ::IpqIpPacket::updateChecksums(), IPQ::IpqTcpPacket::updateChecksums(), updateChecksums(), and NERD::ConnectionServer::handlePacket().
struct iphdr & IPQ::IpqIpPacket::getIpHeader () [read, inherited]
Retrieve the complete IP header of a packet.
A reference to the packet's IP header.
Note:
This method sets the packet's dirty flag, requiring that the packet's checksums be recomputed before a verdict is set.
Definition at line 853 of file IPQ.cpp.
References IPQ::IpqPacket::dirty, and IPQ::IpqIpPacket::doGetIpHeader().
const boost::uint8_t * IPQ::IpqIpPacket::getIpPayload (std::size_t & size) const [inherited]
Retrive the IP payload of a packet.
Parameters:
[out] size A reference to a location to store the packet's IP payload size, in bytes..
Returns:
A const pointer to the packet's IP payload.
Definition at line 867 of file IPQ.cpp.
References IPQ::IpqIpPacket::doGetIpPayload().
boost::uint8_t * IPQ::IpqIpPacket::getIpPayload (std::size_t & size) [inherited]
Retrive the IP payload of a packet.
Parameters:
[out] size A reference to a location to store the packet's IP payload size, in bytes..
Returns:
A pointer to the packet's IP payload.
Note:
This method sets the packet's dirty flag, requiring that the packet's checksums be recomputed before a verdict is set.
Definition at line 882 of file IPQ.cpp.
References IPQ::IpqPacket::dirty, and IPQ::IpqIpPacket::doGetIpPayload().
in_addr_t IPQ::IpqIpPacket::getIpSource () const [inherited]
Retrieve the source IP address of a packet.
Returns:
The packet's source IP address.
Definition at line 772 of file IPQ.cpp.
References IPQ::IpqIpPacket::getIpHeader().
Referenced by IPQ::IpqIpPacket::print(), and NERD::ConnectionServer::handlePacket().
bool IPQ::IpqIpPacket::getMoreFrags () const [inherited]
Retrieve the "more fragments to follow" flag of a packet.
Returns:
true if the packet's "more fragments" flag is set; false otherwise.
Definition at line 829 of file IPQ.cpp.
References IPQ::IpqIpPacket::getIpHeader().
Referenced by IPQ::IpqIpPacket::print(), and NERD::ConnectionServer::handlePacket().
unsigned IPQ::IpqPacket::getNfHook () const [inherited]
Retrieve the number of the Netfilter hook on which the packet arrived.
Returns:
The number of the Netfilter hook on which the packet arrived.
Definition at line 553 of file IPQ.cpp.
References IPQ::IpqPacket::packet, and LibWheel::auto_array::get().
Referenced by IPQ::IpqPacket::print().
unsigned long IPQ::IpqPacket::getNfId () const [inherited]
Retrieve the Netfilter ID of a packet.
Returns:
The packet's Netfilter ID.
Definition at line 519 of file IPQ.cpp.
References IPQ::IpqPacket::packet, and LibWheel::auto_array::get().
Referenced by IPQ::IpqSocket::recvPacket(), and IPQ::IpqPacket::print().
unsigned long IPQ::IpqPacket::getNfMark () const [inherited]
Retrieve the Netfilter mark value of a packet.
Returns:
The packet's Netfilter mark value.
Definition at line 530 of file IPQ.cpp.
References IPQ::IpqPacket::packet, and LibWheel::auto_array::get().
Referenced by IPQ::IpqPacket::print().
const char(& IPQ::IpqPacket::getOutdevName ())[IFNAMSIZ] [inherited]
Retrieve the name of the interface on which the packet will leave, if available.
Returns:
A reference to the packet's outbound interface name.
Definition at line 574 of file IPQ.cpp.
Referenced by IPQ::IpqPacket::print().
const boost::uint8_t * IPQ::IpqPacket::getPacket (std::size_t & size) const [inherited]
Retrieve the packet.
It will only be available if the copy mode on the libipq handle used to receive it was IpqSocket::PACKET and the copy range was greater than zero.
Parameters:
[out] size A reference to a location to write the length of the payload, in bytes.
Returns:
A const pointer to the packet.
Definition at line 624 of file IPQ.cpp.
References IPQ::IpqPacket::doGetPacket().
Referenced by IPQ::IpqSocket::recvPacket().
boost::uint8_t * IPQ::IpqPacket::getPacket (std::size_t & size) [inherited]
Retrieve the packet.
It will only be available if the copy mode on the libipq handle used to receive it was IpqSocket::PACKET and the copy range was greater than zero.
Parameters:
[out] size A reference to a location to write the length of the payload, in bytes.
Returns:
A pointer to the packet.
Note:
This method sets the packet's dirty flag, requiring that the packet's checksums be recomputed before a verdict is set.
Definition at line 641 of file IPQ.cpp.
References IPQ::IpqPacket::dirty, and IPQ::IpqPacket::doGetPacket().
boost::uint8_t IPQ::IpqIpPacket::getProtocol () const [inherited]
Retrieve the encapsulated protocol number of a packet.
Returns:
The packet's encapsulated protocol number.
Definition at line 794 of file IPQ.cpp.
References IPQ::IpqIpPacket::getIpHeader().
Referenced by IPQ::IpqIpPacket::print(), and NERD::ConnectionServer::handlePacket().
void IPQ::IpqPacket::getTimestamp (struct timeval & time) const [inherited]
Retrieve the arrival time of a packet.
Returns:
The packet's arrival time.
Definition at line 541 of file IPQ.cpp.
References IPQ::IpqPacket::packet, and LibWheel::auto_array::get().
Referenced by IPQ::IpqPacket::print().
in_port_t IPQ::IpqUdpPacket::getUdpDest () const
Retrieve the UDP destination port of a packet.
Returns:
The packet's UDP destination port.
Definition at line 1237 of file IPQ.cpp.
References getUdpHeader().
Referenced by print(), and NERD::ConnectionServer::handlePacket().
struct udphdr & IPQ::IpqUdpPacket::getUdpHeader () const [read]
Retrieve the complete UDP header of a packet.
A const reference to the packet's UDP header.
Definition at line 1248 of file IPQ.cpp.
References doGetUdpHeader().
Referenced by getUdpSource(), getUdpDest(), updateChecksums(), and NERD::ConnectionServer::handlePacket().
struct udphdr & IPQ::IpqUdpPacket::getUdpHeader () [read]
Retrieve the complete UDP header of a packet.
A reference to the packet's UDP header.
Note:
This method sets the packet's dirty flag, requiring that the packet's checksums be recomputed before a verdict is set.
Definition at line 1261 of file IPQ.cpp.
References IPQ::IpqPacket::dirty, and doGetUdpHeader().
const boost::uint8_t * IPQ::IpqUdpPacket::getUdpPayload (std::size_t & size) const
Retrive the UDP payload of a packet.
Parameters:
[out] size A reference to a location to store the packet's UDP payload size, in bytes..
Returns:
A pointer to the packet's UDP payload.
Definition at line 1275 of file IPQ.cpp.
References doGetUdpPayload().
boost::uint8_t * IPQ::IpqUdpPacket::getUdpPayload (std::size_t & size)
Retrive the UDP payload of a packet.
Parameters:
[out] size A reference to a location to store the packet's UDP payload size, in bytes..
Returns:
A pointer to the packet's UDP payload.
Note:
This method sets the packet's dirty flag, requiring that the packet's checksums be recomputed before a verdict is set.
Definition at line 1290 of file IPQ.cpp.
References IPQ::IpqPacket::dirty, and doGetUdpPayload().
in_port_t IPQ::IpqUdpPacket::getUdpSource () const
Retrieve the UDP source port of a packet.
Returns:
The packet's UDP source port.
Definition at line 1226 of file IPQ.cpp.
References getUdpHeader().
Referenced by print(), and NERD::ConnectionServer::handlePacket().
void IPQ::IpqUdpPacket::print (std::ostream & out) const [virtual]
Print a TCP packet to stdout in an easy-to-read format.
Reimplemented from IPQ::IpqIpPacket.
Definition at line 1301 of file IPQ.cpp.
References getUdpSource(), and getUdpDest().
void IPQ::IpqUdpPacket::updateChecksums () [protected, virtual]
Update the checksums on an UDP packet.
Note:
If NO_NF_STOP is defined, then the modified flag is set if the old checksum value is different than the new one.
Reimplemented from IPQ::IpqIpPacket.
Definition at line 1365 of file IPQ.cpp.
References getUdpHeader(), IPQ::IpqPacket::packet, LibWheel::auto_array::get(), IPQ::IpqIpPacket::getIpHeader(), and IPQ::ip_checksum().
Friends And Related Function Documentation
IpqPacket* IpqPacket::createPacket (LibWheel::auto_array< boost::uint8_t > , std::size_t) [friend]
Allow IpqSocket::createPacket() to access the contstructor.
Reimplemented from IPQ::IpqIpPacket.
Member Data Documentation
bool IPQ::IpqPacket::dirty [protected, inherited]
true if the packet has been modified but checksums have not been updated; false otherwise.
Definition at line 171 of file IPQ.hpp.
Referenced by IPQ::IpqPacket::getPacket(), IPQ::IpqPacket::updateChecksums(), IPQ::IpqIpPacket::getIpHeader(), IPQ::IpqIpPacket::getIpPayload(), IPQ::IpqTcpPacket::getTcpHeader(), IPQ::IpqTcpPacket::getTcpPayload(), getUdpHeader(), and getUdpPayload().
LibWheel::auto_array<boost::uint8_t> IPQ::IpqPacket::packet [protected, inherited]
The packet message received from kernelspace.
Definition at line 169 of file IPQ.hpp.
Referenced by IPQ::IpqPacket::getNfId(), IPQ::IpqPacket::getNfMark(), IPQ::IpqPacket::getTimestamp(), IPQ::IpqPacket::getNfHook(), IPQ::IpqPacket::getHwProtocol(), IPQ::IpqPacket::getHwType(), IPQ::IpqPacket::print(), IPQ::IpqPacket::doGetPacket(), IPQ::IpqIpPacket::doGetIpHeader(), IPQ::IpqIpPacket::doGetIpPayload(), IPQ::IpqTcpPacket::doGetTcpHeader(), IPQ::IpqTcpPacket::doGetTcpPayload(), IPQ::IpqTcpPacket::updateChecksums(), doGetUdpHeader(), doGetUdpPayload(), and updateChecksums().
std::size_t IPQ::IpqPacket::packetLen [protected, inherited]
the length of the packet message in IpqPacket::packet, in bytes.
Definition at line 170 of file IPQ.hpp.
The documentation for this class was generated from the following files:
IPQ.hpp
IPQ.cpp