Network Rerouter Daemon (nerd): LibWheel::SignalQueue Class Reference
LibWheel::SignalQueue Class Reference
A system for synchronously handling asynchronous signals in a uni-threaded process.
#include <Signals.hpp>
Classes
struct Pipe
Convienience wrapper for a non-blocking Unix pipe.
Public Types
enum Action { DEFAULT, IGNORE, HANDLE }
Possible ways to handle a signal.
Static Public Member Functions
static void setHandler (int sig, Action act) throw (std::domain_error, std::invalid_argument)
Set the action to perform when a signal is received.
static void addHandler (int sig, boost::function< void()> act) throw (std::invalid_argument)
Add a handler function for a signal.
template<typename T >
static void deleteHandler (int sig, const T &act) throw (std::invalid_argument)
Unregister a handler for a signal.
static void deleteHandlers (int sig) throw (std::invalid_argument)
Remove all handlers for a signal.
static void handleNext ()
Call all handlers for the next signal in the signal pipe.
static void handleAll ()
Call all handlers for all signals in the signal pipe.
static bool pending () throw (std::runtime_error)
Check if any signals are pending in the signal queue.
static int getReadFD ()
Retrieve the read file descriptor of the signal pipe.
static int select (int n, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timeval *timeout)
Wait for an event to occur on a file descriptor.
Private Types
typedef std::list
< boost::function< void()> > HandlerList
The type of a set of handlers for a particular signal.
Private Member Functions
friend void::SignalQueue_signalHandler (int, siginfo_t *, void *)
This needs to call getSignalPipe().
Static Private Member Functions
static const Pipe & getSignalPipe ()
Retrieve the signal pipe used by SignalQueue.
static HandlerList * getSignalTable ()
Retrieve the table of signal handlers.
Detailed Description
A system for synchronously handling asynchronous signals in a uni-threaded process.
Users can request that certain signals be handled, and can register any number of arbitrary functions to handle them. When a signal arrives, all that is done is that its number is written to a pipe. The user can then poll for pending signals from the pipe using SignalQueue::pending() or by calling poll() or select() on SignalQueue::getReadFD(), and can execute all handlers for pending signals using SignalQueue::handleNext() and SignalQueue::handleAll(). Handlers are executed in the order that they were registered. SignalQueue::select() is provided as an version of select() that waits for file descriptors to change status, while handling any signals that arrive in the meantime.
Signal handlers can be either functions or functors that take no parameters and return void. Since they are called synchronously from normal program flow, they can safely perform any action, including throw exceptions. (SignalException is provided for this purpose.)
Since SignalQueue only has static methods, it could simply be a namespace (rather than a class). However, I couldn't get a non-template version of deleteHandler() to work properly, so its definition needs to be inline, and it needs to call getSignalTable(), which should be private. If this was a namespace, getSignalTable() and all the other private stuff could be static to Signals.cpp.
Member Typedef Documentation
typedef std::list<boost::function<void()> > LibWheel::SignalQueue::HandlerList [private]
The type of a set of handlers for a particular signal.
Definition at line 120 of file Signals.hpp.
Member Enumeration Documentation
enum LibWheel::SignalQueue::Action
Possible ways to handle a signal.
Enumerator:
DEFAULT
Take the operating systems's default action for the signal.
IGNORE
Ignore the signal.
HANDLE
Call all registered signal handlers when a signal is received.
Definition at line 129 of file Signals.hpp.
Member Function Documentation
void LibWheel::SignalQueue::addHandler (int sig, boost::function< void()> act) throw (std::invalid_argument) [static]
Add a handler function for a signal.
Parameters:
sig The signal for which the handler is to be added.
act The handler to add.
Exceptions:
std::invalid_argument If sig is invalid.
Definition at line 234 of file Signals.cpp.
References getSignalTable().
Referenced by NERD::ConnectionServer::ConnectionServer(), main(), LibWheel::Timer::Timer(), and LibWheel::WaitList::WaitList().
template<typename T > void LibWheel::SignalQueue::deleteHandler (int sig, const T & act) throw (std::invalid_argument) [static]
Unregister a handler for a signal.
Parameters:
sig A signal number.
act A reference to the signal handler to unregister for sig.
Exceptions:
std::invalid_argument If sig is not a valid signal number.
Definition at line 156 of file Signals.hpp.
Referenced by NERD::ConnectionServer::~ConnectionServer(), LibWheel::Timer::~Timer(), and LibWheel::WaitList::~WaitList().
void LibWheel::SignalQueue::deleteHandlers (int sig) throw (std::invalid_argument) [static]
Remove all handlers for a signal.
Parameters:
sig The signal whose handlers to remove.
Exceptions:
std::invalid_argument If sig is invalid.
Definition at line 249 of file Signals.cpp.
References getSignalTable().
int LibWheel::SignalQueue::getReadFD () [static]
Retrieve the read file descriptor of the signal pipe.
It may be used to poll for pending signals using poll() or select(); reading from it will cause signals to be lost.
Returns:
The file descriptor of the signal pipe.
Definition at line 334 of file Signals.cpp.
References getSignalPipe(), and LibWheel::SignalQueue::Pipe::fds.
Referenced by NERD::ConnectionServer::operator()(), handleNext(), pending(), and select().
const SignalQueue::Pipe & LibWheel::SignalQueue::getSignalPipe () [static, private]
Retrieve the signal pipe used by SignalQueue.
Returns:
A reference to SignalQueue's signal pipe.
Definition at line 165 of file Signals.cpp.
Referenced by setHandler(), getReadFD(), and SignalQueue_signalHandler().
SignalQueue::HandlerList * LibWheel::SignalQueue::getSignalTable () [static, private]
Retrieve the table of signal handlers.
Returns:
A pointer to the signal handler table (an array of _NSIG elements).
Definition at line 178 of file Signals.cpp.
Referenced by addHandler(), deleteHandlers(), and handleNext().
void LibWheel::SignalQueue::handleAll () [static]
Call all handlers for all signals in the signal pipe.
Exceptions:
Anything that a registered signal handler throws.
Definition at line 293 of file Signals.cpp.
References pending(), and handleNext().
Referenced by select().
void LibWheel::SignalQueue::handleNext () [static]
Call all handlers for the next signal in the signal pipe.
Exceptions:
Anything that a registered signal handler throws.
Definition at line 263 of file Signals.cpp.
References getReadFD(), and getSignalTable().
Referenced by NERD::ConnectionServer::operator()(), and handleAll().
bool LibWheel::SignalQueue::pending () throw (std::runtime_error) [static]
Check if any signals are pending in the signal queue.
Returns:
true if a signal is pending; false otherwise.
Exceptions:
std::runtime_error If there is an error checking the signal queue.
Definition at line 306 of file Signals.cpp.
References getReadFD(), and select().
Referenced by handleAll().
int LibWheel::SignalQueue::select (int n, fd_set * readfds, fd_set * writefds, fd_set * exceptfds, struct timeval * timeout) [static]
Wait for an event to occur on a file descriptor.
This works identically to select(), except that any signals that are delivered before an event occurs are handled. See the man page for select() for details.
Parameters:
n The highest-numbered file descriptor in readfds, writefds and exceptfds, plus 1.
readfds A set of file descriptors to watch for avaiable data to read.
writefds A set of file descriptors to watch for the possibility of writing data without blocking.
exceptfds A set of file descriptors to watch for exceptional conditions.
timeout An upper bound on the time to wait for events to occur. If it is zero, select() will return immediately. If it is null, select() will block indefinately.
Definition at line 357 of file Signals.cpp.
References getReadFD(), and handleAll().
Referenced by pending().
void LibWheel::SignalQueue::setHandler (int sig, Action act) throw (std::domain_error, std::invalid_argument) [static]
Set the action to perform when a signal is received.
Parameters:
sig The signal whose action to set.
act The action to perform when signal is received.
Exceptions:
std::domain_error If act is invalid.
std::invalid_argument If sig is invalid.
Definition at line 193 of file Signals.cpp.
References DEFAULT, IGNORE, HANDLE, SignalQueue_signalHandler(), and getSignalPipe().
Referenced by NERD::ConnectionServer::ConnectionServer(), main(), LibWheel::Timer::Timer(), and LibWheel::WaitList::WaitList().
LibWheel::SignalQueue::void::SignalQueue_signalHandler (int , siginfo_t * , void *) [private]
This needs to call getSignalPipe().
The documentation for this class was generated from the following files:
Signals.hpp
Signals.cpp