Network Rerouter Daemon (nerd): NERD::ConnectionServer::ServerWritebackHandler Class Reference
NERD::ConnectionServer::ServerWritebackHandler Class Reference
Functor to handle SIGIO signals received through LibWheel::SignalQueue.
Public Member Functions
ServerWritebackHandler (PendingConnectionList &pcl, RedirectionTable &rt, ServerTable &st, IPQ::IpqSocket &s)
Constructor for ServerWritebackHandler.
void operator() ()
Call operator for ServerWritebackHandler.
Private Attributes
PendingConnectionList & pendingConnections
A reference to the containing ConnectionServer's list of pending connections.
RedirectionTable & redirections
A reference to the containing ConnectionServer's table of redirection rules.
ServerTable & servers
A reference to the containing ConnectionServer's look-up table of active servers.
IPQ::IpqSocket & sock
A handle to libipq.
Detailed Description
Functor to handle SIGIO signals received through LibWheel::SignalQueue.
When a server process writes its listen port number to its stdout, that triggers a SIGIO; this functor determines which servers have called back and finishes setting up connections to them. See operator()() for details.
Constructor & Destructor Documentation
NERD::ConnectionServer::ServerWritebackHandler::ServerWritebackHandler (PendingConnectionList & pcl, RedirectionTable & rt, ServerTable & st, IPQ::IpqSocket & s)
Constructor for ServerWritebackHandler.
Parameters:
pcl A reference to the containing ConnectionServer's list of pending connections.
rt A reference to the containing ConnectionServer's look-up table of redirection rules.
st A reference to the containing ConnectionServer's look-up table of active servers.
s A handle to libipq.
Definition at line 809 of file nerd.cpp.
Member Function Documentation
void NERD::ConnectionServer::ServerWritebackHandler::operator() ()
Call operator for ServerWritebackHandler.
For all pending servers that have written data to stdout (the write ends of pipes whose read ends are held in the list of pending connections), read a port number, establish redirection rules for packet travelling to and from the server, add the server to the active servers table and remove it from the pending connections list, and forward the inital packet to the server.
Note:
This is an O(n) operation in the number of pending connections.
Side Effects:
May write messages to LibWheel::logmsg.
Definition at line 825 of file nerd.cpp.
References NERD::ConnectionServer::pendingConnections, LibWheel::WaitList::begin(), LibWheel::WaitList::end(), LibWheel::uninterruptible_read(), LibWheel::logmsg, logmsg_err, LibWheel::WaitList::erase(), logmsg_info, LibWheel::ipv4_to_string(), LOCALHOST_IP, MAGIC_PORT, NERD::ConnectionServer::servers, NERD::ConnectionServer::redirections, NERD::ConnectionServer::sock, and IPQ::IpqSocket::sendResponse().
Member Data Documentation
PendingConnectionList& NERD::ConnectionServer::ServerWritebackHandler::pendingConnections [private]
A reference to the containing ConnectionServer's list of pending connections.
Definition at line 263 of file nerd.cpp.
RedirectionTable& NERD::ConnectionServer::ServerWritebackHandler::redirections [private]
A reference to the containing ConnectionServer's table of redirection rules.
Definition at line 264 of file nerd.cpp.
ServerTable& NERD::ConnectionServer::ServerWritebackHandler::servers [private]
A reference to the containing ConnectionServer's look-up table of active servers.
Definition at line 265 of file nerd.cpp.
IPQ::IpqSocket& NERD::ConnectionServer::ServerWritebackHandler::sock [private]
A handle to libipq.
Definition at line 266 of file nerd.cpp.
The documentation for this class was generated from the following file:
nerd.cpp