Network Rerouter Daemon (nerd): LibWheel::auto_array Class Reference
LibWheel::auto_array Class Reference
A simple smart pointer for arrays that provides strict ownership semantics in the manner of std::auto_ptr.
#include <auto_array.hpp>
Classes
struct auto_array_ref
A wrapper class to provide auto_array with reference semantics.
Public Types
typedef T element_type
The type of the contained array.
Public Member Functions
auto_array (element_type *p=0) throw ()
Constructs an auto_array from a pointer to a dynamically allocated array.
auto_array (auto_array< T > &a) throw ()
Constructs an auto_array from another auto_array.
auto_array< element_type > & operator= (auto_array< T > &a) throw ()
Assign one auto_array to another.
auto_array< element_type > & operator= (auto_array_ref ref) throw ()
Assign an auto_array_ref to an auto_array.
~auto_array () throw ()
Destructor for auto_array.
element_type & operator[] (std::size_t i) const throw ()
Index operator for auto_array.
element_type * get () const throw ()
Retrieves a pointer to the currently-owned array.
element_type * release () throw ()
Releases ownership of the currently-owned array.
void reset (element_type *p=0) throw ()
Frees and drops ownership of the currently-owned array, and takes ownership of a new array.
auto_array (auto_array_ref ref) throw ()
Constructs an auto_array from an auto_array_ref.
operator auto_array_ref () throw ()
Converts an auto_array into an auto_array_ref.
Private Attributes
T * ptr
The array owned by this auto_array.
Detailed Description
A simple smart pointer for arrays that provides strict ownership semantics in the manner of std::auto_ptr.
Despite what the C++ standard guys will tell you, it isn't always possible to use std::vector in place of an array. For intance, you may need to call a C or external library API that requires an array. This class provides automatic destruction in the manner of std::auto_ptr for true arrays.
Member Typedef Documentation
typedef T LibWheel::auto_array::element_type
The type of the contained array.
Definition at line 60 of file auto_array.hpp.
Constructor & Destructor Documentation
LibWheel::auto_array::auto_array (element_type * p = 0) throw () [explicit]
Constructs an auto_array from a pointer to a dynamically allocated array.
The constructed auto_array will own the array pointed to by p.
Parameters:
p A pointer to a dynamically-allocated array.
Warning:
Constructing an auto_array from a pointer to a single object, statically-allocated array, or anything else not allocated with new[] results in undefined behaviour.
Definition at line 90 of file auto_array.hpp.
LibWheel::auto_array::auto_array (auto_array< T > & a) throw ()
Constructs an auto_array from another auto_array.
The constructed auto_array will own the array originally owned by a.
Parameters:
a Another auto_array of the same type.
Side Effects:
a will loose ownership of its array.
Definition at line 102 of file auto_array.hpp.
LibWheel::auto_array::~auto_array () throw ()
Destructor for auto_array.
Frees the memory held by this auto_array.
Definition at line 127 of file auto_array.hpp.
References ptr.
LibWheel::auto_array::auto_array (auto_array_ref ref) throw ()
Constructs an auto_array from an auto_array_ref.
The constructed auto_array owns the array pointed to by ref.
Parameters:
ref An auto_array_ref of the same type.
Definition at line 204 of file auto_array.hpp.
Member Function Documentation
T * LibWheel::auto_array::get () const throw ()
Retrieves a pointer to the currently-owned array.
Ownership is not changed.
Returns:
A pointer to the currently-owned array.
Definition at line 157 of file auto_array.hpp.
References ptr.
Referenced by IPQ::IpqSocket::recvPacket(), IPQ::IpqPacket::getNfId(), IPQ::IpqPacket::getNfMark(), IPQ::IpqPacket::getTimestamp(), IPQ::IpqPacket::getNfHook(), IPQ::IpqPacket::getHwProtocol(), IPQ::IpqPacket::getHwType(), IPQ::IpqPacket::print(), IPQ::IpqPacket::doGetPacket(), IPQ::IpqPacket::createPacket(), IPQ::IpqIpPacket::doGetIpHeader(), IPQ::IpqIpPacket::doGetIpPayload(), IPQ::IpqTcpPacket::doGetTcpHeader(), IPQ::IpqTcpPacket::doGetTcpPayload(), IPQ::IpqTcpPacket::updateChecksums(), IPQ::IpqUdpPacket::doGetUdpHeader(), IPQ::IpqUdpPacket::doGetUdpPayload(), and IPQ::IpqUdpPacket::updateChecksums().
LibWheel::auto_array::operator auto_array_ref () throw ()
Converts an auto_array into an auto_array_ref.
Ownership of the currently-owned array is dropped.
Returns:
An auto_array_ref containing a pointer to the array formerly owned by this auto_array.
Definition at line 231 of file auto_array.hpp.
References release().
auto_array< T > & LibWheel::auto_array::operator= (auto_array< T > & a) throw ()
Assign one auto_array to another.
The array owned by this auto_array will be deleted, and this auto_array will take ownership of the array originally owned by a.
Parameters:
a Another auto_array of the same type.
Side Effects:
a will loose ownership of its array.
Definition at line 116 of file auto_array.hpp.
References reset().
auto_array< T > & LibWheel::auto_array::operator= (auto_array_ref ref) throw ()
Assign an auto_array_ref to an auto_array.
The array owned by this auto_array will be deleted, and this auto_array will take ownersnip of the array pointed to by ref.
Parameters:
ref An auto_array_ref of the same type.
Definition at line 217 of file auto_array.hpp.
References reset().
T & LibWheel::auto_array::operator[] (std::size_t i) const throw ()
Index operator for auto_array.
Retrieves an element from this auto_array.
Parameters:
i The index of the element to retrieve.
Returns:
The element of the currently-owned array at index i.
Warning:
No bounds checks are made. Supplying a value of i outside of the bounds of the currently-owned array results in undefined behaviour.
Definition at line 144 of file auto_array.hpp.
References ptr.
T * LibWheel::auto_array::release () throw ()
Releases ownership of the currently-owned array.
The caller is then responsible for managing it.
Returns:
A pointer to the currently-owned array.
Definition at line 170 of file auto_array.hpp.
References ptr.
Referenced by operator auto_array_ref().
void LibWheel::auto_array::reset (element_type * p = 0) throw ()
Frees and drops ownership of the currently-owned array, and takes ownership of a new array.
Parameters:
p A pointer to a dynamically-allocated array.
Warning:
Assigning ownership of a single object, statically-allocated array, or anything else not allocated with new[] to an auto_arrayresults in undefined behaviour.
Definition at line 188 of file auto_array.hpp.
References ptr.
Referenced by operator=().
Member Data Documentation
T* LibWheel::auto_array::ptr [private]
The array owned by this auto_array.
Definition at line 57 of file auto_array.hpp.
Referenced by ~auto_array(), operator[](), get(), release(), and reset().
The documentation for this class was generated from the following file:
auto_array.hpp