Network Rerouter Daemon (nerd): LibWheel::Logmsg Class Reference
LibWheel::Logmsg Class Reference
A C++ front-end to logmsg: a generic framework for logging error or status messages to various targets.
#include <Logmsg.hpp>
Public Member Functions
bool isOpen () const
Check if a Logmsg object is open.
int open (logmsg_target_t target, unsigned options, const char *name)
Open and initialize a target.
int operator() (logmsg_priority_t priority, const char *format,...)
Prints a message to the current target.
int close ()
Shuts down the logmsg facility.
Static Public Member Functions
static Logmsg & getLogmsg ()
Retrieve the global Logmsg object.
Private Member Functions
Logmsg ()
Initialize a Logmsg object in a closed state.
~Logmsg ()
Destructor for Logmsg.
Private Attributes
bool isopen
true if this logger is currently open; false otherwise
Detailed Description
A C++ front-end to logmsg: a generic framework for logging error or status messages to various targets.
See also:
logmsg.c
logmsg.h
Constructor & Destructor Documentation
LibWheel::Logmsg::Logmsg () [private]
Initialize a Logmsg object in a closed state.
Definition at line 45 of file Logmsg.cpp.
LibWheel::Logmsg::~Logmsg () [private]
Destructor for Logmsg.
Closes the target if it's open.
Definition at line 53 of file Logmsg.cpp.
References isopen, and close().
Member Function Documentation
int LibWheel::Logmsg::close ()
Shuts down the logmsg facility.
Closes the target appropriately.
Returns:
0 on success, or EOF on failure, with errno set appropriately.
See also:
logmsg_close()
Definition at line 109 of file Logmsg.cpp.
References isopen, and logmsg_close().
Referenced by ~Logmsg().
Logmsg & LibWheel::Logmsg::getLogmsg () [static]
Retrieve the global Logmsg object.
Returns:
a reference to the global Logmsg object.
Definition at line 35 of file Logmsg.cpp.
bool LibWheel::Logmsg::isOpen () const
Check if a Logmsg object is open.
Returns:
true if it's open; false otherwise.
Definition at line 65 of file Logmsg.cpp.
References isopen.
int LibWheel::Logmsg::open (logmsg_target_t target, unsigned options, const char * name)
Open and initialize a target.
If a target is already open, close it first.
Parameters:
target The type of target to use.
options A bitfield of option flags.
name A string whose purpose is determined by the value of target:
logmsg_file: The name of the file to use.
logmsg_syslog, logmsg_stdout, logmsg_stderr: A string to prepend to each log message.
Returns:
0 on success or -1 on failure, with errno set appropriately.
See also:
logmsg_open()
Definition at line 85 of file Logmsg.cpp.
References isopen, logmsg_close(), and logmsg_open().
int LibWheel::Logmsg::operator() (logmsg_priority_t priority, const char * format, ...)
Prints a message to the current target.
The message is formatted \ according to syslog() conventions.
Parameters:
priority The message priority. How this is interpreted depends on the target:
logmsg_syslog: Use the equivalent syslog priority.
logmsg_file, logmsg_stdout, logmsg_stderr: Prepend a string to the message indicating the priority
format A printf()-style format string, followed by arguments.
Returns:
0 on success, or -1 on failure
See also:
logmsg()
Definition at line 133 of file Logmsg.cpp.
References isopen, and vlogmsg().
Member Data Documentation
bool LibWheel::Logmsg::isopen [private]
true if this logger is currently open; false otherwise
Definition at line 43 of file Logmsg.hpp.
Referenced by ~Logmsg(), isOpen(), open(), close(), and operator()().
The documentation for this class was generated from the following files:
Logmsg.hpp
Logmsg.cpp