Network Rerouter Daemon (nerd): IPQ::IpqPacket Class Reference
IPQ::IpqPacket Class Reference
Base class for packets received via IpqSocket.
#include <IPQ.hpp>
Public Member Functions
virtual ~IpqPacket ()
Destructor for IpqPacket.
unsigned long getNfId () const
Retrieve the Netfilter ID of a packet.
unsigned long getNfMark () const
Retrieve the Netfilter mark value of a packet.
void getTimestamp (struct timeval &time) const
Retrieve the arrival time of a packet.
unsigned getNfHook () const
Retrieve the number of the Netfilter hook on which the packet arrived.
const char(& getIndevName () const)[IFNAMSIZ]
Retrieve the name of the interface on which the packet arrived, if available.
const char(& getOutdevName () const)[IFNAMSIZ]
Retrieve the name of the interface on which the packet will leave, if available.
unsigned short getHwProtocol () const
Retrieve the hardware protocol number of the packet.
unsigned short getHwType () const
Retrieve the hardware type on which the packet arrived.
const unsigned char(& getHwSource (unsigned short &addrlen) const)[8]
Retrieve the source hardware address of the packet.
const boost::uint8_t * getPacket (std::size_t &size) const
Retrieve the packet.
boost::uint8_t * getPacket (std::size_t &size)
Retrieve the packet.
virtual void print (std::ostream &out) const
Print a packet to stdout in an easy-to-read format.
Protected Member Functions
IpqPacket (LibWheel::auto_array< boost::uint8_t > buf, std::size_t buflen)
Constructor for IpqPacket.
boost::uint8_t * doGetPacket (std::size_t &size) const
Retrieve the packet.
virtual void updateChecksums ()
Update the packet's checksums and clear the dirty flag.
Static Protected Member Functions
static IpqPacket * createPacket (LibWheel::auto_array< boost::uint8_t > buf, std::size_t buflen)
Create an IpqPacket or one of its subclasses from a libipq packet message.
Protected Attributes
LibWheel::auto_array
< boost::uint8_t > packet
The packet message received from kernelspace.
std::size_t packetLen
the length of the packet message in IpqPacket::packet, in bytes.
bool dirty
true if the packet has been modified but checksums have not been updated; false otherwise.
Private Attributes
bool responseSent
true if a verdict has been set on this packet; false otherwise.
Friends
IpqPacket * IpqSocket::recvPacket (bool)
Allow IpqSocket::recvPacket() to access createPacket().
void IpqSocket::sendResponse (IpqPacket *, Verdict)
Allow IpqSocket::sendResponse() to access IpqPacket::responseSent and IpqPacket::dirty.
Detailed Description
Base class for packets received via IpqSocket.
Contains all packet metadata fields, plus the original packet message from kernelspace.
A verdict must be set on each packet exactly once. When IpqSocket::sendResponse() is used to set a verdict on a packet, the packet is flagged so that no new verdict can be set. If no verdict is set, the destructor to IpqPacket will set a verdict of DROP.
Note:
Allowing copies of IpqPackets to be made would break the responseSent checking. If it becomes necessary to make copies at some point, create an IpqPacketBuffer class that contains all of the data and getters, but not responseSet or the setters. Have IpqPacket inherit that, add the setters, give it a private copy constructor and assignment operator, and write an assignment operator that allows IpqPackets to be safely assigned to IpqPacketBuffers. The only way to create an IpqPacket should be from within IpqSocket::recvPacket().
Constructor & Destructor Documentation
IPQ::IpqPacket::~IpqPacket () [virtual]
Destructor for IpqPacket.
If no response has been set for this packet, attempt to set a response of DROP, and discard any exceptions thrown.
Definition at line 500 of file IPQ.cpp.
References responseSent, IPQ::IpqSocket::getSocket(), IPQ::IpqSocket::sendResponse(), and IPQ::IpqSocket::DROP.
IPQ::IpqPacket::IpqPacket (LibWheel::auto_array< boost::uint8_t > buf, std::size_t buflen) [protected]
Constructor for IpqPacket.
Initialize an IpqPacket from a libipq packet message.
Definition at line 685 of file IPQ.cpp.
Referenced by createPacket().
Member Function Documentation
IpqPacket * IPQ::IpqPacket::createPacket (LibWheel::auto_array< boost::uint8_t > buf, std::size_t buflen) [static, protected]
Create an IpqPacket or one of its subclasses from a libipq packet message.
A packet will be deemed to be an IPv4 packet if it has a full IPv4 header and the data length indicated by the header matches the packet's length. A packet will be deemed to be a TCP or UDP packet if it is an IPv4 packet and it has a full TCP or UDP header.
Returns:
A pointer to a dynamically-allocated IpqPacket, or one of its subclasses. This pointer must be freed using delete, and a verdict should be set on it using IpqSocket::sendResponse().
Definition at line 731 of file IPQ.cpp.
References LibWheel::auto_array::get(), and IpqPacket().
Referenced by IPQ::IpqSocket::recvPacket().
boost::uint8_t * IPQ::IpqPacket::doGetPacket (std::size_t & size) const [protected]
Retrieve the packet.
It will only be available if the copy mode on the libipq handle used to receive it was IpqSocket::PACKET and the copy range was greater than zero.
Parameters:
[out] size A reference to a location to write the length of the payload, in bytes.
Returns:
A pointer to the packet.
Definition at line 703 of file IPQ.cpp.
References packet, and LibWheel::auto_array::get().
Referenced by getPacket().
unsigned short IPQ::IpqPacket::getHwProtocol () const
Retrieve the hardware protocol number of the packet.
Returns:
The packet's hardware protocol number.
Definition at line 585 of file IPQ.cpp.
References packet, and LibWheel::auto_array::get().
Referenced by print().
const unsigned char(& IPQ::IpqPacket::getHwSource (unsigned short & addrlen))[8]
Retrieve the source hardware address of the packet.
Parameters:
[out] addrlen A reference to a location to write the actual length of the address, in bytes.
Returns:
A reference to the packet's source hardware address.
Definition at line 608 of file IPQ.cpp.
Referenced by print().
unsigned short IPQ::IpqPacket::getHwType () const
Retrieve the hardware type on which the packet arrived.
Returns:
The packet's arrival hardware type.
Definition at line 596 of file IPQ.cpp.
References packet, and LibWheel::auto_array::get().
Referenced by print().
const char(& IPQ::IpqPacket::getIndevName ())[IFNAMSIZ]
Retrieve the name of the interface on which the packet arrived, if available.
Returns:
A reference to the packet's arrival interface name.
Definition at line 563 of file IPQ.cpp.
Referenced by print().
unsigned IPQ::IpqPacket::getNfHook () const
Retrieve the number of the Netfilter hook on which the packet arrived.
Returns:
The number of the Netfilter hook on which the packet arrived.
Definition at line 553 of file IPQ.cpp.
References packet, and LibWheel::auto_array::get().
Referenced by print().
unsigned long IPQ::IpqPacket::getNfId () const
Retrieve the Netfilter ID of a packet.
Returns:
The packet's Netfilter ID.
Definition at line 519 of file IPQ.cpp.
References packet, and LibWheel::auto_array::get().
Referenced by IPQ::IpqSocket::recvPacket(), and print().
unsigned long IPQ::IpqPacket::getNfMark () const
Retrieve the Netfilter mark value of a packet.
Returns:
The packet's Netfilter mark value.
Definition at line 530 of file IPQ.cpp.
References packet, and LibWheel::auto_array::get().
Referenced by print().
const char(& IPQ::IpqPacket::getOutdevName ())[IFNAMSIZ]
Retrieve the name of the interface on which the packet will leave, if available.
Returns:
A reference to the packet's outbound interface name.
Definition at line 574 of file IPQ.cpp.
Referenced by print().
const boost::uint8_t * IPQ::IpqPacket::getPacket (std::size_t & size) const
Retrieve the packet.
It will only be available if the copy mode on the libipq handle used to receive it was IpqSocket::PACKET and the copy range was greater than zero.
Parameters:
[out] size A reference to a location to write the length of the payload, in bytes.
Returns:
A const pointer to the packet.
Definition at line 624 of file IPQ.cpp.
References doGetPacket().
Referenced by IPQ::IpqSocket::recvPacket().
boost::uint8_t * IPQ::IpqPacket::getPacket (std::size_t & size)
Retrieve the packet.
It will only be available if the copy mode on the libipq handle used to receive it was IpqSocket::PACKET and the copy range was greater than zero.
Parameters:
[out] size A reference to a location to write the length of the payload, in bytes.
Returns:
A pointer to the packet.
Note:
This method sets the packet's dirty flag, requiring that the packet's checksums be recomputed before a verdict is set.
Definition at line 641 of file IPQ.cpp.
References dirty, and doGetPacket().
void IPQ::IpqPacket::getTimestamp (struct timeval & time) const
Retrieve the arrival time of a packet.
Returns:
The packet's arrival time.
Definition at line 541 of file IPQ.cpp.
References packet, and LibWheel::auto_array::get().
Referenced by print().
void IPQ::IpqPacket::print (std::ostream & out) const [virtual]
Print a packet to stdout in an easy-to-read format.
Reimplemented in IPQ::IpqUdpPacket, IPQ::IpqTcpPacket, and IPQ::IpqIpPacket.
Definition at line 652 of file IPQ.cpp.
References getTimestamp(), getHwSource(), getNfId(), getNfMark(), getNfHook(), getIndevName(), getOutdevName(), getHwProtocol(), getHwType(), packet, and LibWheel::auto_array::get().
void IPQ::IpqPacket::updateChecksums () [protected, virtual]
Update the packet's checksums and clear the dirty flag.
Reimplemented in IPQ::IpqUdpPacket, IPQ::IpqTcpPacket, and IPQ::IpqIpPacket.
Definition at line 714 of file IPQ.cpp.
References dirty.
Friends And Related Function Documentation
IpqPacket* IpqSocket::recvPacket (bool) [friend]
Allow IpqSocket::recvPacket() to access createPacket().
void IpqSocket::sendResponse (IpqPacket * , Verdict) [friend]
Allow IpqSocket::sendResponse() to access IpqPacket::responseSent and IpqPacket::dirty.
Member Data Documentation
bool IPQ::IpqPacket::dirty [protected]
true if the packet has been modified but checksums have not been updated; false otherwise.
Definition at line 171 of file IPQ.hpp.
Referenced by getPacket(), updateChecksums(), IPQ::IpqIpPacket::getIpHeader(), IPQ::IpqIpPacket::getIpPayload(), IPQ::IpqTcpPacket::getTcpHeader(), IPQ::IpqTcpPacket::getTcpPayload(), IPQ::IpqUdpPacket::getUdpHeader(), and IPQ::IpqUdpPacket::getUdpPayload().
LibWheel::auto_array<boost::uint8_t> IPQ::IpqPacket::packet [protected]
The packet message received from kernelspace.
Definition at line 169 of file IPQ.hpp.
Referenced by getNfId(), getNfMark(), getTimestamp(), getNfHook(), getHwProtocol(), getHwType(), print(), doGetPacket(), IPQ::IpqIpPacket::doGetIpHeader(), IPQ::IpqIpPacket::doGetIpPayload(), IPQ::IpqTcpPacket::doGetTcpHeader(), IPQ::IpqTcpPacket::doGetTcpPayload(), IPQ::IpqTcpPacket::updateChecksums(), IPQ::IpqUdpPacket::doGetUdpHeader(), IPQ::IpqUdpPacket::doGetUdpPayload(), and IPQ::IpqUdpPacket::updateChecksums().
std::size_t IPQ::IpqPacket::packetLen [protected]
the length of the packet message in IpqPacket::packet, in bytes.
Definition at line 170 of file IPQ.hpp.
bool IPQ::IpqPacket::responseSent [private]
true if a verdict has been set on this packet; false otherwise.
Definition at line 179 of file IPQ.hpp.
Referenced by ~IpqPacket().
The documentation for this class was generated from the following files:
IPQ.hpp
IPQ.cpp