Network Rerouter Daemon (nerd): LibWheel::WaitList Class Reference
LibWheel::WaitList Class Reference
A list from which items will be removed after a timeout.
#include <WaitList.hpp>
Classes
class WaitGC
Timer interrupt handler for WaitList.
class WaitWrapper
Wrapper that attaches a timestamp to objects stored in a WaitList.
Public Types
typedef V value_type
The type of object stored in this WaitList.
typedef std::list< WaitWrapper >
::iterator iterator
A type describing a bidirectional iterator for the list.
typedef std::list< WaitWrapper >
::const_iterator const_iterator
A type describing a constant bidirectional iterator for the list.
Public Member Functions
WaitList (unsigned short time)
Constructor for WaitList.
~WaitList ()
Destructor for WaitList.
iterator begin ()
Retrieves a bidirectional iterator to the beginning of the list.
iterator end ()
Retrieves a bidirectional iterator to just past the end of the list.
const_iterator begin () const
Retrieves a constant bidirectional iterator to the beginning of the list.
const_iterator end () const
Retrieves a constant bidirectional iterator to just past the end of the list.
void add (const value_type &rev)
Adds an object to the back of the list.
iterator erase (iterator &i)
Removes an object from the list.
std::size_t size () const
Retrieves the number of elements in the list.
bool empty () const
Checks if the list is empty.
Protected Attributes
std::list< WaitWrapper > objs
The list of objects contained by this WaitList.
WaitGC gc
The timer interrupt handler for this WaitList.
unsigned short timeout
The lifetime of objects stored in this WaitList, in seconds.
Detailed Description
A list from which items will be removed after a timeout.
When an item is inserted, a timer interrupt is scheduled using Timer. When the interrupt is handled (by calling SignalQueue::handleNext() or SignalQueue::handleAll()), the item will be removed. Additional operations can be performed at this time by specializing WaitList::WaitGC::operator()() for value_type.
The underlying container is std::list.
Bug:
The timer interrupt handler (WaitList::WaitGC) assumes that the list is sorted in chronological order. However, since list iterators are provided, this is not necessarily true. Consequently, objects that are out of chronological order will not be removed until after all objects before them in list order have timed out and been removed.
Warning:
The constructor to WaitList sets a signal handler for SIGALRM through SignalQueue. Don't use this class if you have a handler for SIGALRM outside of SignalQueue or if you're using a library function that uses SIGALRM.
Member Typedef Documentation
typedef std::list<WaitWrapper>::const_iterator LibWheel::WaitList::const_iterator
A type describing a constant bidirectional iterator for the list.
Definition at line 66 of file WaitList.hpp.
typedef std::list<WaitWrapper>::iterator LibWheel::WaitList::iterator
A type describing a bidirectional iterator for the list.
Definition at line 65 of file WaitList.hpp.
typedef V LibWheel::WaitList::value_type
The type of object stored in this WaitList.
Definition at line 64 of file WaitList.hpp.
Constructor & Destructor Documentation
LibWheel::WaitList::WaitList (unsigned short time)
Constructor for WaitList.
Parameters:
time The lifetime of objects stored in this WaitList.
Side Effects:
Sets the signal handler for SIGALRM.
Definition at line 40 of file WaitList_impl.cpp.
References LibWheel::SignalQueue::setHandler(), LibWheel::SignalQueue::HANDLE, LibWheel::SignalQueue::addHandler(), and gc.
LibWheel::WaitList::~WaitList ()
Destructor for WaitList.
Definition at line 52 of file WaitList_impl.cpp.
References LibWheel::SignalQueue::deleteHandler().
Member Function Documentation
void LibWheel::WaitList::add (const value_type & rec)
Adds an object to the back of the list.
Parameters:
rec The object to add.
Side Effects:
Schedules a timer interrupt through Timer.
Definition at line 115 of file WaitList_impl.cpp.
References LibWheel::Timer::getTimer(), and LibWheel::Timer::schedule().
Referenced by NERD::ConnectionServer::ServerExitHandler::operator()(), and NERD::ConnectionServer::createConnection().
WaitList< V >::iterator LibWheel::WaitList::begin ()
Retrieves a bidirectional iterator to the beginning of the list.
Returns:
An iterator to the first item of the list, or just past the end of the list if it is empty.
Definition at line 65 of file WaitList_impl.cpp.
Referenced by NERD::ConnectionServer::ServerExitHandler::findPendingConnection(), and NERD::ConnectionServer::ServerWritebackHandler::operator()().
WaitList< V >::const_iterator LibWheel::WaitList::begin () const
Retrieves a constant bidirectional iterator to the beginning of the list.
Returns:
A const_iterator to the first item of the list, or just past the end of the list if it is empty.
Definition at line 78 of file WaitList_impl.cpp.
bool LibWheel::WaitList::empty () const
Checks if the list is empty.
Returns:
true if the list is empty; false otherwise.
Definition at line 152 of file WaitList_impl.cpp.
WaitList< V >::iterator LibWheel::WaitList::end ()
Retrieves a bidirectional iterator to just past the end of the list.
Returns:
An iterator pointing just past the end of the list
Definition at line 90 of file WaitList_impl.cpp.
Referenced by NERD::ConnectionServer::ServerExitHandler::operator()(), NERD::ConnectionServer::ServerExitHandler::findPendingConnection(), and NERD::ConnectionServer::ServerWritebackHandler::operator()().
WaitList< V >::const_iterator LibWheel::WaitList::end () const
Retrieves a constant bidirectional iterator to just past the end of the list.
Returns:
A const_iterator pointing just past the end of the list
Definition at line 102 of file WaitList_impl.cpp.
WaitList< V >::iterator LibWheel::WaitList::erase (iterator & i)
Removes an object from the list.
Parameters:
i An iterator pointing to the object to remove.
Definition at line 128 of file WaitList_impl.cpp.
Referenced by NERD::ConnectionServer::ServerExitHandler::operator()(), and NERD::ConnectionServer::ServerWritebackHandler::operator()().
std::size_t LibWheel::WaitList::size () const
Retrieves the number of elements in the list.
Returns:
The number of elements in the list.
Definition at line 140 of file WaitList_impl.cpp.
Referenced by NERD::ConnectionServer::printStats().
Member Data Documentation
WaitGC LibWheel::WaitList::gc [protected]
The timer interrupt handler for this WaitList.
Definition at line 94 of file WaitList.hpp.
Referenced by WaitList().
std::list<WaitWrapper> LibWheel::WaitList::objs [protected]
The list of objects contained by this WaitList.
Definition at line 93 of file WaitList.hpp.
Referenced by LibWheel::WaitList::WaitGC::operator()().
unsigned short LibWheel::WaitList::timeout [protected]
The lifetime of objects stored in this WaitList, in seconds.
Definition at line 95 of file WaitList.hpp.
The documentation for this class was generated from the following files:
WaitList.hpp
WaitList_impl.cpp