Network Rerouter Daemon (nerd): IPQ::IpqSocket Class Reference
IPQ::IpqSocket Class Reference
A program's link to libipq.
#include <IPQ.hpp>
Public Types
enum CopyMode { META, PACKET }
The amount of packet information to copy to userspace.
enum Verdict { ACCEPT, DROP, STOP }
The verdict to set on a packet.
Public Member Functions
void connect () throw (IpqException)
Connect to libipq.
void setCopyMode (CopyMode mode, std::size_t range=65535) throw (IpqException)
Sets the libipq copy mode.
IpqPacket * recvPacket (bool noblock=false) throw (IpqException)
Receive a packet from libipq.
void waitForPacket () throw (IpqException)
Wait for a packet to become available.
void waitForPacket (int func_fd, boost::function< void()> func)
Wait for a packet to become available.
void sendResponse (IpqPacket *pkt, Verdict v) throw (IpqException)
Sets the verdict on a packet.
void close () throw (IpqException)
Close the libipq handle.
unsigned long getPacketsReceived () const
Retrieve the number of packets that have been received from libipq.
unsigned long getPacketsAccepted () const
Retrieve the number of packets for which a verdict of ACCEPT or STOP was set.
unsigned long getPacketsDropped () const
Retrieve the number of packets for which a verdict of DROP was set.
Static Public Member Functions
static IpqSocket & getSocket ()
Retrieve the global libipq handle.
Protected Member Functions
IpqSocket ()
Constructor for IpqSocket.
~IpqSocket ()
Destructor for IpqSocket.
Private Attributes
bool isConnected
true on sockets that are connected; false otherwise.
CopyMode copyMode
The amount of packet data to copy from kernelspace.
struct ipq_handle * ipqHandle
Handle to libipq.
unsigned long packetsReceived
The number of packets that have been received.
unsigned long packetsAccepted
The number of packets for which ACCEPT or STOP verdicts have been set.
unsigned long packetsDropped
The number of packets for which DROP verdicts have been set.
Detailed Description
A program's link to libipq.
Only one program can use libipq at a time.
Warning:
This class is not thread-safe.
Bug:
Connect() does not detect if other another program is using libipq. Instead, if another program is connected, recvPacket() will throw an exception. This is due to a limitation in libipq.
Due to a bug in Netfilter, changing the source IP address of a packet to a non-local address and then setting a verdict of NF_ACCEPT will cause it to be dropped. This has been observed when the packet was queued from the OUTPUT chain of the mangle table. A work-around is to set a verdict of NF_STOP instead of NF_ACCEPT, but be aware that this results in the packet being treated differently by iptables. Kernels prior to 2.6.12 do not have NF_STOP; defining NO_NF_STOP enables another work-around: all packets are immediately dropped, and packets that are to be accepted are re-injected through raw sockets. In this case, care must be taken to ensure that infinite queueing loops do not occur. Also, this work-around only works for IP packets.
Member Enumeration Documentation
enum IPQ::IpqSocket::CopyMode
The amount of packet information to copy to userspace.
Enumerator:
META
Copy packet medatada only.
PACKET
Copy both packet metadata and contents.
Definition at line 85 of file IPQ.hpp.
enum IPQ::IpqSocket::Verdict
The verdict to set on a packet.
Enumerator:
ACCEPT
Accept the packet and continue iptables traversal.
DROP
Drop the packet.
STOP
Accept the packet, but don't continue iptables traversal.
Definition at line 90 of file IPQ.hpp.
Constructor & Destructor Documentation
IPQ::IpqSocket::IpqSocket () [protected]
Constructor for IpqSocket.
Initialize an unconnected libipq handle.
Definition at line 453 of file IPQ.cpp.
IPQ::IpqSocket::~IpqSocket () [protected]
Destructor for IpqSocket.
If the handle is open, close it and discard any exceptions thrown.
Definition at line 468 of file IPQ.cpp.
References close().
Member Function Documentation
void IPQ::IpqSocket::close () throw (IpqException)
Close the libipq handle.
If the handle is not open, no action is taken.
Exceptions:
IpqException If an error was encountered closing the handle.
Warning:
Do not close the handle without ensuring that verdicts have been set on all packets received. Since the destructor to IpqPacket attempts to set a verdict on unresponded packets, Bad Things (tm) will happen if the handle is closed.
Definition at line 243 of file IPQ.cpp.
References isConnected, and ipqHandle.
Referenced by ~IpqSocket(), and NERD::ConnectionServer::~ConnectionServer().
void IPQ::IpqSocket::connect () throw (IpqException)
Connect to libipq.
Sets the default copy mode to metadata only. If NO_NF_STOP is defined, open raw_sock as well.
Exceptions:
IpqException If the socket is already connected or there is an error connecting.
Definition at line 113 of file IPQ.cpp.
References isConnected, ipqHandle, setCopyMode(), and META.
unsigned long IPQ::IpqSocket::getPacketsAccepted () const
Retrieve the number of packets for which a verdict of ACCEPT or STOP was set.
Returns:
The number of packets accepted.
Definition at line 432 of file IPQ.cpp.
References packetsAccepted.
Referenced by NERD::ConnectionServer::printStats().
unsigned long IPQ::IpqSocket::getPacketsDropped () const
Retrieve the number of packets for which a verdict of DROP was set.
Returns:
The number of packets dropped.
Definition at line 443 of file IPQ.cpp.
References packetsDropped.
Referenced by NERD::ConnectionServer::printStats().
unsigned long IPQ::IpqSocket::getPacketsReceived () const
Retrieve the number of packets that have been received from libipq.
Returns:
The number of packets received.
Definition at line 421 of file IPQ.cpp.
References packetsReceived.
Referenced by NERD::ConnectionServer::printStats().
IpqSocket & IPQ::IpqSocket::getSocket () [static]
Retrieve the global libipq handle.
Returns:
A reference to the global libipq handle.
Definition at line 99 of file IPQ.cpp.
Referenced by IPQ::IpqPacket::~IpqPacket().
IpqPacket * IPQ::IpqSocket::recvPacket (bool noblock = false) throw (IpqException)
Receive a packet from libipq.
Parameters:
noblock If true, throw an IpqException if no packet is available. If false, block until a packet becomes available. (default: false)
Returns:
A dynamically-allocated packet object, which may be an IpqPacket or any of its subclasses. It must be freed using delete, and a verdict should be set on it using IpqSocket::sendResponse().
Exceptions:
IpqException If there was an error reading from the socket, no packet was immediately available and noblock was set, or a libipq error message was received.
Note:
If noblock was not set, then this method may block indefinately.
If NO_NF_STOP is defined, the packet is immediately dropped. It may be re-injected using IpqSocket::sendResponse().
Definition at line 277 of file IPQ.cpp.
References LibWheel::auto_array::get(), IPQ::IpqPacket::createPacket(), IPQ::IpqPacket::getPacket(), and IPQ::IpqPacket::getNfId().
Referenced by NERD::ConnectionServer::operator()().
void IPQ::IpqSocket::sendResponse (IpqPacket * pkt, Verdict v) throw (IpqException)
Sets the verdict on a packet.
If the packet was changed, the original packet will be replaced with the modified version. If a verdict was already set on pkt, no action is taken beyond updating the packet checksums.
Parameters:
pkt The packet whose verdict to set.
v The verdict to set.
Exceptions:
IpqException If the verdict is invalid or there was an error setting the verdict.
Note:
If NO_NF_STOP is set, a verdict cannot be safely set, so a copy of the packet in injected through a raw socket. Care must be taken to avoid infinite loops.
Definition at line 177 of file IPQ.cpp.
References NF_STOP, LibWheel::arraySize(), and IPQ::IpqIpPacket::getIpDest().
Referenced by IPQ::IpqPacket::~IpqPacket(), NERD::ConnectionServer::ServerWritebackHandler::operator()(), NERD::ConnectionServer::handlePacket(), and NERD::ConnectionServer::createConnection().
void IPQ::IpqSocket::setCopyMode (CopyMode mode, std::size_t range = 65535) throw (IpqException)
Sets the libipq copy mode.
Parameters:
mode The libipq copy mode.
range The number of packet payload bytes to copy (default: 65535). This is only used if mode is PACKET.
Exceptions:
IpqException if the socket is not connected, the mode is invalid, or there is an error setting the mode.
Definition at line 145 of file IPQ.cpp.
References LibWheel::arraySize().
Referenced by connect().
void IPQ::IpqSocket::waitForPacket () throw (IpqException)
Wait for a packet to become available.
Exceptions:
IpqException If an error was encountered checking for a packet.
Note:
This method may block indefinately.
Definition at line 362 of file IPQ.cpp.
References ipqHandle.
Referenced by NERD::ConnectionServer::operator()().
void IPQ::IpqSocket::waitForPacket (int func_fd, boost::function< void()> func)
Wait for a packet to become available.
If input becomes available on func_fd before a packet arrives, call func, and resume waiting.
Note:
This method may block indefinately.
Definition at line 384 of file IPQ.cpp.
References ipqHandle.
Member Data Documentation
CopyMode IPQ::IpqSocket::copyMode [private]
The amount of packet data to copy from kernelspace.
Definition at line 114 of file IPQ.hpp.
struct ipq_handle* IPQ::IpqSocket::ipqHandle [private]
Handle to libipq.
Definition at line 115 of file IPQ.hpp.
Referenced by connect(), close(), and waitForPacket().
bool IPQ::IpqSocket::isConnected [private]
true on sockets that are connected; false otherwise.
Definition at line 113 of file IPQ.hpp.
Referenced by connect(), and close().
unsigned long IPQ::IpqSocket::packetsAccepted [private]
The number of packets for which ACCEPT or STOP verdicts have been set.
Definition at line 118 of file IPQ.hpp.
Referenced by getPacketsAccepted().
unsigned long IPQ::IpqSocket::packetsDropped [private]
The number of packets for which DROP verdicts have been set.
Definition at line 119 of file IPQ.hpp.
Referenced by getPacketsDropped().
unsigned long IPQ::IpqSocket::packetsReceived [private]
The number of packets that have been received.
Definition at line 117 of file IPQ.hpp.
Referenced by getPacketsReceived().
The documentation for this class was generated from the following files:
IPQ.hpp
IPQ.cpp