Network Rerouter Daemon (nerd): NERD::ConnectionServer Class Reference
NERD::ConnectionServer Class Reference
The main class for the Network Rerouter Daemon (nerd).
Classes
struct AddressPair
The source and destination addresses of IP packets travelling in one direction in a connection.
class AddressPairHash
A functor that computes a hash of an AddressPair, suitable for use with __gnu_cxx::hash_map.
class Connection
A description of a connection managed by a server program.
struct PendingConnection
Information pertaining to a server that is starting up to handle a connection.
class ServerExitHandler
Functor to handle SIGCHLD signals received through LibWheel::SignalQueue.
struct ServerRecord
Information about a server program to be started.
class ServerWritebackHandler
Functor to handle SIGIO signals received through LibWheel::SignalQueue.
class UnknownConnectionException
Exception thrown by getRedirectRule() when a packet does not match any existing connection record.
class UnknownServerException
Exception thrown by findServer() when no server program can be found to handle a new connection.
Public Types
typedef LibWheel::WaitList
< PendingConnection > PendingConnectionList
A list of pending connections.
typedef LibWheel::WaitList
< std::pair< RedirectionTable
*, RedirectionTable::iterator > > TimeoutList
A list of redirection rules that are scheduled to be deleted at their expiry of timers.
Public Member Functions
ConnectionServer (const std::string &root, bool verb, bool restrict) throw (IPQ::IpqException, LibWheel::IOException, LibWheel::SocketException)
Constructor for ConnectionServer.
~ConnectionServer ()
Destructor for ConnectionServer.
void operator() ()
Main loop for ConnectionServer.
void printStats () const
Print current server status to LibWheel::logmsg.
Private Types
typedef __gnu_cxx::hash_map
< AddressPair, AddressPair,
AddressPairHash > RedirectionTable
A look-up table mapping the addresses of packets to redirection rules.
typedef __gnu_cxx::hash_map
< pid_t, Connection > ServerTable
A look-up table mapping server process IDs to the connections that they manage.
Private Member Functions
void handlePacket (IPQ::IpqPacket *pkt)
Handle a packet.
const AddressPair & getRedirectRule (const IPQ::IpqTcpPacket *pkt) const throw (UnknownConnectionException)
Looks up a redirection rule for a TCP packet.
const AddressPair & getRedirectRule (const IPQ::IpqUdpPacket *pkt) const throw (UnknownConnectionException)
Looks up a redirection rule for a UDP packet.
void createConnection (IPQ::IpqTcpPacket *pkt)
Creates a TCP connection.
void createConnection (IPQ::IpqUdpPacket *pkt)
Creates a UDP connection.
void findServer (ServerRecord &rec, in_addr_t addr) const throw (UnknownServerException)
Attempts to find a server program to run in response to a connection request.
bool isExecutable (const std::string &file) const
Determines if a file is executable.
Private Attributes
IPQ::IpqSocket & sock
A handle to libipq.
const std::string serverRoot
The directory in which to search for server programs.
bool verbose
true to log extra messages; false otherwise
PendingConnectionList pendingConnections
The list of servers (and associated initial packets) which have been started but have not yet responded with packet numbers.
RedirectionTable redirections
A hash table of rules governing packet redirections for open conncetions.
TimeoutList timeoutList
A list of redirection rules to be deleted when timeouts expire.
ServerTable servers
A hash table of server process IDs and the connections that they handle.
ServerExitHandler exitHandler
The functor that handles SIGCHLD signals when servers exit.
ServerWritebackHandler writebackHandler
The functor that handles SIGIO signals when servers write back their port numbers.
bool restrict_servers
true to limit the privileges of server programs; false otherwise.
int magic_sock
A socket bound to 127.0.0.1:MAGIC_PORT/TCP.
Detailed Description
The main class for the Network Rerouter Daemon (nerd).
Responsible for receiving packets from kernelspace via libipq, launching servers to handle them, creating and tracking connections, and forwarding packets.
Packets are received from kernelspace in operator(), from which they are passed to handlePacket() for handling. If a packet is part of an existing connection, it are redirected to its destination server from there. Otherwise, createConnection() is called to create a connection. If an appropriate server can be found (see findServer()), then the server is launched and the packet queued pending a message from the server indicating the port that it is using. Otherwise, the packet is accepted without modification.
Servers are responsible for writing their listen port numbers to stdout (file descriptor 1) as two-byte messages in network byte order. If this does not occur within 10 seconds of a server starting, then it is assumed to be malfunctioning, is sent a SIGINT, and is dropped. The initial packet associated with such a server is accepted unmodified.
Notification that a server has written its port number back comes through SIGIO signals, which are handled synchronously by a functor of type ConnectionServer::ServerWritebackHandler in operator() via LibWheel::SignalQueue. This functor creates redirection rules for packets travelling both too and from the server.
Connections are closed when SIGCHLD is received from their server processes, indicating that they have exited. A function of type ServerExitHandler is responsible for handling SIGCHID, again through LibWheel::SignalQueue. Connection redirection rules persist for NERD_CONNECTION_TIMEOUT seconds after their servers exit.
SIGALRM is used internally to implement timeouts. As with all other signals used in this program, it is handled synchronously through LibWheel::SignalQueue.
Bug:
As described above, servers that have not responded within 10 seconds are assumed to be malfunctioning and are dropped. However, if the server is in fact still running, it will exit when it receives the SIGINT or at some later time. This will result in a warning message indicating that SIGCHLD was received from a process for which no record exists. This could probably be fixed, but an extra log message is not currently considered to be a problem worthy of the effort required to fix it.
Member Typedef Documentation
typedef LibWheel::WaitList<PendingConnection> NERD::ConnectionServer::PendingConnectionList
A list of pending connections.
Note:
This type is public because specializations of LibWheel::WaitList are outsideof this class.
Definition at line 207 of file nerd.cpp.
typedef __gnu_cxx::hash_map<AddressPair, AddressPair, AddressPairHash> NERD::ConnectionServer::RedirectionTable [private]
A look-up table mapping the addresses of packets to redirection rules.
Definition at line 163 of file nerd.cpp.
typedef __gnu_cxx::hash_map<pid_t, Connection> NERD::ConnectionServer::ServerTable [private]
A look-up table mapping server process IDs to the connections that they manage.
Definition at line 186 of file nerd.cpp.
typedef LibWheel::WaitList<std::pair<RedirectionTable*, RedirectionTable::iterator> > NERD::ConnectionServer::TimeoutList
A list of redirection rules that are scheduled to be deleted at their expiry of timers.
Note:
This type is public because specializations of LibWheel::WaitList are outsideof this class.
Definition at line 215 of file nerd.cpp.
Constructor & Destructor Documentation
NERD::ConnectionServer::ConnectionServer (const std::string & root, bool verb, bool restrict) throw (IPQ::IpqException, LibWheel::IOException, LibWheel::SocketException)
Constructor for ConnectionServer.
Connect to libipq, register handlers for SIGCHLD and SIGIO with LibWheel::SignalQueue, and perform other initialization tasks.
Parameters:
root The directory in which to search for server programs.
verb true to enable verbose logging; false otherwise.
restrict true to restrict server privileges; false otherwise.
Exceptions:
IPQ::IpqException If there is an error initializing libipq.
LibWheel::IOException If root is not a readable directory.
LibWheel::SocketException If MAGIC_PORT cannot be bound to.
Definition at line 413 of file nerd.cpp.
References IPQ::IpqSocket::PACKET, QUOTE, MAGIC_PORT, LOCALHOST_IP, LibWheel::SignalQueue::setHandler(), LibWheel::SignalQueue::HANDLE, and LibWheel::SignalQueue::addHandler().
NERD::ConnectionServer::~ConnectionServer ()
Destructor for ConnectionServer.
Unregisters signal handlers for SIGIO and SIGCHLD from LibWheel::SignalQueue and shuts down libipq.
Definition at line 463 of file nerd.cpp.
References LibWheel::SignalQueue::deleteHandler(), writebackHandler, exitHandler, magic_sock, sock, IPQ::IpqSocket::close(), LibWheel::logmsg, and logmsg_err.
Member Function Documentation
void NERD::ConnectionServer::createConnection (IPQ::IpqTcpPacket * pkt) [private]
Creates a TCP connection.
If a program can be found to handle the connection (see ConnectionServer::findServer()), then this program fork()s and attempts to execute it in the child process. If no server can be found, if it cannot be launched, or some other error occurs, the packet is immediately accepted and a message may be logged to LibWheel::logmsg.
The child process is executed with stdout set to the write end of a pipe whose read end is held by the parent. The read end is set in non-blocking, signal-driven mode; its file descriptor, along with the packet, the server program name, and the child process' PID, is added to a list accessible to the SIGIO handler (which works through LibWheel::SignalQueue). This handler is responsible for creating the connection and accepting the packet.
If restrict_servers is set, the child program is executed under the UID and GID of the owner of the program. If the program is accessed through a symbolic link, the UID and GID of the link must match those of the target.
Parameters:
pkt A packet that initializes a TCP connection. If the TCP SYN flag is not set on pkt, a message is logged and it is accepted immediately.
Bug:
Checking program ownership and using execve() to launch it results in a TOCTOU race condition. The solution is to use fexecve(). However, Linux does not currently implement the fexecve() system call, and its emulation in glibc does not work on Linux kernels prior to 2.6.22-rc1 if the calling program has called setuid() or seteuid(). This may have been fixed in Linux 2.6.22-rc1. When a version of fexecve() that does work becomes available, undefine the macro BROKEN_FEXECVE in the makefile to use fexecve() instead of execve().
Side Effects:
Writes messages to LibWheel::logmsg.
Definition at line 1062 of file nerd.cpp.
References IPQ::IpqTcpPacket::getTcpHeader(), verbose, LibWheel::logmsg, logmsg_err, sock, IPQ::IpqSocket::sendResponse(), IPQ::IpqSocket::ACCEPT, LibWheel::ipv4_to_string(), IPQ::IpqIpPacket::getIpDest(), IPQ::IpqTcpPacket::getTcpDest(), findServer(), LibWheel::uninterruptible_close(), pendingConnections, LibWheel::WaitList::add(), NERD::ConnectionServer::ServerRecord::serverProgram, logmsg_info, NERD_PIPE_FD, restrict_servers, LibWheel::close_files_on_exec(), drop_priv(), NERD::ConnectionServer::ServerRecord::serverAddr, NERD::ConnectionServer::ServerRecord::serverPort, NERD::ConnectionServer::ServerRecord::serverDnsRecord, and logmsg_warning.
Referenced by handlePacket().
void NERD::ConnectionServer::createConnection (IPQ::IpqUdpPacket * pkt) [private]
Creates a UDP connection.
This is not currently implemented, so a warning is logged and the packet is accepted.
Parameters:
pkt A packet that initializes a UDP connection.
Definition at line 1238 of file nerd.cpp.
References verbose, LibWheel::logmsg, logmsg_warning, sock, IPQ::IpqSocket::sendResponse(), and IPQ::IpqSocket::ACCEPT.
void NERD::ConnectionServer::findServer (ServerRecord & rec, in_addr_t addr) const throw (UnknownServerException) [private]
Attempts to find a server program to run in response to a connection request.
The following attempts are made:
search for a program named rec.serverAddr:rec.serverPort in serverRoot (example: 10.1.1.1:23)
search for a program named rec.serverAddr in serverRoot (example: 10.1.1.1)
perform a DNS query for a TXT record for serverAddr to get a semicolon-separated list of key=value pairs, and search for a program whose name is given by the value associated with the key P<rec.serverPort> in serverRoot (example: D=foobar.com;P25=smtpserver;P80=webserver). If more than one DNS TXT record is found, only the first one is used and a warning is logged.
If no server program is found using any of these methods, an UnknownServerException is thrown.
Parameters:
rec A description of the connection requested. The following fields must be set when this function is called:
ServerRecord::serverAddr
ServerRecord::serverPort
ServerRecord::serverProto
When this function returns, the ServerRecord::serverProgram filled will be filled with the name of the program to run, and the ServerRecord::serverDnsRecord field may be filled with the DNS TXT record for the server's IP address.
addr The IP address of the requested server, in host byte order.
Exceptions:
UnknownServerException If no server program can be found for the requested server.
Side Effects:
May write messages to LibWheel::logmsg.
Definition at line 1278 of file nerd.cpp.
References serverRoot, isExecutable(), LibWheel::getDnsTxt(), LibWheel::logmsg, logmsg_warning, LibWheel::ipv4_to_string(), verbose, logmsg_info, NERD::DnsServerRecord::getValue(), NERD::DnsServerRecord::end(), and logmsg_err.
Referenced by createConnection().
const ConnectionServer::AddressPair & NERD::ConnectionServer::getRedirectRule (const IPQ::IpqTcpPacket * pkt) const throw (UnknownConnectionException) [private]
Looks up a redirection rule for a TCP packet.
Parameters:
pkt The packet to look up.
Returns:
The redirection rule for pkt, if it exists.
Exceptions:
UnknownConnectionException If no redirection rule for pkt exists.
Definition at line 1002 of file nerd.cpp.
References redirections.
Referenced by handlePacket().
const ConnectionServer::AddressPair & NERD::ConnectionServer::getRedirectRule (const IPQ::IpqUdpPacket * pkt) const throw (UnknownConnectionException) [private]
Looks up a redirection rule for a UDP packet.
UDP connection are not currently implemented, so this method simply throws an UnknownConnectionException.
Returns:
Theoretically, the redirection rule for the packet, but this is not currently implemented.
Exceptions:
UnknownConnectionException If no redirection rule for the packet exists.
Definition at line 1023 of file nerd.cpp.
void NERD::ConnectionServer::handlePacket (IPQ::IpqPacket * packet) [private]
Handle a packet.
If the packet is part of a pre-existing connection, redirect the packet accordingly. Otherwise, attempt to create a connection for the packet.
Currently, IP fragments and non-TCP/IP packets are not supported. Packets of these types will be accepted unmodified, and messages will be logged to LibWheel::logmsg.
Parameters:
packet The packet to redirect.
Bug:
There is a bug in netfilter that causes locally-generated outbound packets with non-local source IP addresses to be dropped. Since packets returning to a client program from a server match this description after being redirected, they must be accepted with NF_STOP rather than NF_ACCEPT. This means that they do not continue iptables traversal, and cannot be filtered elsewhere in iptables.
Definition at line 894 of file nerd.cpp.
References IPQ::IpqIpPacket::getMoreFrags(), IPQ::IpqIpPacket::getFragOffset(), LibWheel::logmsg, logmsg_warning, sock, IPQ::IpqSocket::sendResponse(), IPQ::IpqSocket::ACCEPT, getRedirectRule(), logmsg_info, LibWheel::ipv4_to_string(), IPQ::IpqIpPacket::getIpSource(), IPQ::IpqTcpPacket::getTcpSource(), IPQ::IpqIpPacket::getIpDest(), IPQ::IpqTcpPacket::getTcpDest(), IPQ::IpqIpPacket::getIpHeader(), IPQ::IpqTcpPacket::getTcpHeader(), LOCALHOST_IP, IPQ::IpqSocket::STOP, createConnection(), IPQ::IpqUdpPacket::getUdpSource(), IPQ::IpqUdpPacket::getUdpDest(), IPQ::IpqUdpPacket::getUdpHeader(), and IPQ::IpqIpPacket::getProtocol().
Referenced by operator()().
bool NERD::ConnectionServer::isExecutable (const std::string & file) const [private]
Determines if a file is executable.
Parameters:
file The file to check for executability.
Returns:
true if file exists and is executable by the current user; false otherwise.
Note:
If file cannot be accessed or exists but is not executable, a message is logged to LibWheel::logmsg.
Definition at line 1347 of file nerd.cpp.
References LibWheel::logmsg, and logmsg_err.
Referenced by findServer().
void NERD::ConnectionServer::operator() ()
Main loop for ConnectionServer.
Receive packets from libipq and pass them off to ConnectionServer::handlePacket for processing; stop when SIGINT is received. All signals that arrive through SignalQueue are also processed from this method.
Definition at line 490 of file nerd.cpp.
References sock, IPQ::IpqSocket::waitForPacket(), LibWheel::SignalQueue::getReadFD(), LibWheel::SignalQueue::handleNext(), IPQ::IpqSocket::recvPacket(), handlePacket(), LibWheel::logmsg, logmsg_err, and logmsg_notice.
void NERD::ConnectionServer::printStats () const
Print current server status to LibWheel::logmsg.
Definition at line 528 of file nerd.cpp.
References LibWheel::logmsg, logmsg_info, redirections, timeoutList, LibWheel::WaitList::size(), pendingConnections, servers, LibWheel::open_files(), sock, IPQ::IpqSocket::getPacketsReceived(), IPQ::IpqSocket::getPacketsAccepted(), and IPQ::IpqSocket::getPacketsDropped().
Referenced by NERD::StatPrinter::operator()().
Member Data Documentation
ServerExitHandler NERD::ConnectionServer::exitHandler [private]
The functor that handles SIGCHLD signals when servers exit.
Definition at line 286 of file nerd.cpp.
Referenced by ~ConnectionServer().
int NERD::ConnectionServer::magic_sock [private]
A socket bound to 127.0.0.1:MAGIC_PORT/TCP.
Definition at line 289 of file nerd.cpp.
Referenced by ~ConnectionServer().
PendingConnectionList NERD::ConnectionServer::pendingConnections [private]
The list of servers (and associated initial packets) which have been started but have not yet responded with packet numbers.
Definition at line 282 of file nerd.cpp.
Referenced by printStats(), NERD::ConnectionServer::ServerExitHandler::operator()(), NERD::ConnectionServer::ServerExitHandler::findPendingConnection(), NERD::ConnectionServer::ServerWritebackHandler::operator()(), and createConnection().
RedirectionTable NERD::ConnectionServer::redirections [private]
A hash table of rules governing packet redirections for open conncetions.
Definition at line 283 of file nerd.cpp.
Referenced by printStats(), NERD::ConnectionServer::ServerExitHandler::operator()(), NERD::ConnectionServer::ServerWritebackHandler::operator()(), and getRedirectRule().
bool NERD::ConnectionServer::restrict_servers [private]
true to limit the privileges of server programs; false otherwise.
Definition at line 288 of file nerd.cpp.
Referenced by createConnection().
const std::string NERD::ConnectionServer::serverRoot [private]
The directory in which to search for server programs.
Definition at line 280 of file nerd.cpp.
Referenced by findServer().
ServerTable NERD::ConnectionServer::servers [private]
A hash table of server process IDs and the connections that they handle.
Definition at line 285 of file nerd.cpp.
Referenced by printStats(), NERD::ConnectionServer::ServerExitHandler::operator()(), and NERD::ConnectionServer::ServerWritebackHandler::operator()().
IPQ::IpqSocket& NERD::ConnectionServer::sock [private]
A handle to libipq.
Definition at line 279 of file nerd.cpp.
Referenced by ~ConnectionServer(), operator()(), printStats(), NERD::ConnectionServer::ServerWritebackHandler::operator()(), handlePacket(), and createConnection().
TimeoutList NERD::ConnectionServer::timeoutList [private]
A list of redirection rules to be deleted when timeouts expire.
Definition at line 284 of file nerd.cpp.
Referenced by printStats(), and NERD::ConnectionServer::ServerExitHandler::operator()().
bool NERD::ConnectionServer::verbose [private]
true to log extra messages; false otherwise
Definition at line 281 of file nerd.cpp.
Referenced by NERD::ConnectionServer::ServerExitHandler::operator()(), createConnection(), and findServer().
ServerWritebackHandler NERD::ConnectionServer::writebackHandler [private]
The functor that handles SIGIO signals when servers write back their port numbers.
Definition at line 287 of file nerd.cpp.
Referenced by ~ConnectionServer().
The documentation for this class was generated from the following file:
nerd.cpp