Network Rerouter Daemon (nerd): NERD::ConnectionServer::ServerExitHandler Class Reference
NERD::ConnectionServer::ServerExitHandler Class Reference
Functor to handle SIGCHLD signals received through LibWheel::SignalQueue.
Public Member Functions
ServerExitHandler (PendingConnectionList &pcl, RedirectionTable &rt, ServerTable &st, TimeoutList &tl, bool v)
Constructor for ServerExitHandler.
void operator() ()
Call operator for ServerExitHandler.
Private Member Functions
PendingConnectionList::iterator findPendingConnection (pid_t pid)
Look up a pending connection given the PID of its server.
Private Attributes
PendingConnectionList & pendingConnections
A reference to the containing ConnectionServer's list of pending connections.
RedirectionTable & redirections
A reference to the containing ConnectionServer's table of redirection rules.
ServerTable & servers
A reference to the containing ConnectionServer's look-up table of active servers.
TimeoutList & timeoutList
A reference to the containing ConnectionServer's list of redirection rules awaiting removal.
bool verbose
true to log extra messages; false otherwise.
Detailed Description
Functor to handle SIGCHLD signals received through LibWheel::SignalQueue.
Performs appropriate actions when a child process exits; see operator()() for details.
Constructor & Destructor Documentation
NERD::ConnectionServer::ServerExitHandler::ServerExitHandler (PendingConnectionList & pcl, RedirectionTable & rt, ServerTable & st, TimeoutList & tl, bool v)
Constructor for ServerExitHandler.
Parameters:
pcl A reference to the containing ConnectionServer's list of pending connections.
rt A reference to the containing ConnectionServer's look-up table of redirection rules.
st A reference to the containing ConnectionServer's look-up table of active servers.
tl A reference to the containing ConnectionServer's list of connections to drop.
v true to enable verbose logging; false otherwise.
Definition at line 701 of file nerd.cpp.
Member Function Documentation
ConnectionServer::PendingConnectionList::iterator NERD::ConnectionServer::ServerExitHandler::findPendingConnection (pid_t pid) [private]
Look up a pending connection given the PID of its server.
Parameters:
pid The process ID of a server.
Returns:
An iterator into the pending connections list if a patching element is found, or to just past the end of the list if none is found.
Note:
This is an O(n) operation in the number of pending connections.
Definition at line 791 of file nerd.cpp.
References NERD::ConnectionServer::pendingConnections, LibWheel::WaitList::begin(), and LibWheel::WaitList::end().
void NERD::ConnectionServer::ServerExitHandler::operator() ()
Call operator for ServerExitHandler.
For each child process that has exited, retrieve the PID and exit status. If the child was associated with an active connection, remove its associated redirection rules, and remove it from the active connections table. Otherwise, if the child was associated with a pending connection, remove it from the pending connections list.
Redirection rules for servers that have exited are added to timeoutList; they will be deleted NERD_CONNECTION_TIMEOUT seconds after their server exited.
Side Effects:
May write messages to LibWheel::logmsg.
Definition at line 719 of file nerd.cpp.
References LibWheel::logmsg, logmsg_err, NERD::ConnectionServer::servers, NERD::ConnectionServer::pendingConnections, LibWheel::WaitList::end(), logmsg_warning, LibWheel::WaitList::erase(), NERD::ConnectionServer::verbose, logmsg_notice, NERD::ConnectionServer::redirections, NERD::ConnectionServer::timeoutList, and LibWheel::WaitList::add().
Member Data Documentation
PendingConnectionList& NERD::ConnectionServer::ServerExitHandler::pendingConnections [private]
A reference to the containing ConnectionServer's list of pending connections.
Definition at line 244 of file nerd.cpp.
RedirectionTable& NERD::ConnectionServer::ServerExitHandler::redirections [private]
A reference to the containing ConnectionServer's table of redirection rules.
Definition at line 245 of file nerd.cpp.
ServerTable& NERD::ConnectionServer::ServerExitHandler::servers [private]
A reference to the containing ConnectionServer's look-up table of active servers.
Definition at line 246 of file nerd.cpp.
TimeoutList& NERD::ConnectionServer::ServerExitHandler::timeoutList [private]
A reference to the containing ConnectionServer's list of redirection rules awaiting removal.
Definition at line 247 of file nerd.cpp.
bool NERD::ConnectionServer::ServerExitHandler::verbose [private]
true to log extra messages; false otherwise.
Definition at line 248 of file nerd.cpp.
The documentation for this class was generated from the following file:
nerd.cpp