Network Rerouter Daemon (nerd): LibWheel::Timer Class Reference
LibWheel::Timer Class Reference
Singleton class to manage real time timer interrupts.
#include <Signals.hpp>
Classes
class Handler
SignalQueue interrupt handler for SIGALRM that schedules the next timer interrupt.
Public Member Functions
void schedule (unsigned short seconds)
Schedule a timer interrupt for seconds seconds from the current time.
Static Public Member Functions
static Timer & getTimer ()
Retrieve the global Timer object.
Private Types
typedef std::priority_queue
< time_t, std::vector< time_t >
, std::greater< time_t > > QueueType
The type of the queue of signal delivery times.
Private Member Functions
Timer ()
Initialize a Timer object.
~Timer ()
Destructor for Timer.
Private Attributes
QueueType times
Queue of signal delivery times.
Handler handler
SignalQueue SIGALRM interrupt handler functor.
Detailed Description
Singleton class to manage real time timer interrupts.
Causes SIGALRMs to be sent to the calling processes at requested times. These signals must then be handled using SignalQueue.
Member Typedef Documentation
typedef std::priority_queue<time_t, std::vector<time_t>, std::greater<time_t> > LibWheel::Timer::QueueType [private]
The type of the queue of signal delivery times.
Definition at line 185 of file Signals.hpp.
Constructor & Destructor Documentation
LibWheel::Timer::Timer () [private]
Initialize a Timer object.
Side Effects:
Registers a signal handler for SIGALRM through SignalQueue.
Definition at line 474 of file Signals.cpp.
References LibWheel::SignalQueue::setHandler(), LibWheel::SignalQueue::HANDLE, LibWheel::SignalQueue::addHandler(), and handler.
LibWheel::Timer::~Timer () [private]
Destructor for Timer.
Side Effects:
Unregisters the timer signal handler from SignalQueue; no further timer interrupts will be scheduled.
Definition at line 487 of file Signals.cpp.
References LibWheel::SignalQueue::deleteHandler(), and handler.
Member Function Documentation
Timer & LibWheel::Timer::getTimer () [static]
Retrieve the global Timer object.
Returns:
A reference to the global Timer object.
Definition at line 395 of file Signals.cpp.
Referenced by LibWheel::WaitList::add().
void LibWheel::Timer::schedule (unsigned short seconds)
Schedule a timer interrupt for seconds seconds from the current time.
Parameters:
seconds The interval until the requested timer interrupt, in seconds. If seconds is 0, no interrupt is scheduled.
Definition at line 408 of file Signals.cpp.
Referenced by LibWheel::WaitList::add().
Member Data Documentation
Handler LibWheel::Timer::handler [private]
SignalQueue SIGALRM interrupt handler functor.
Definition at line 202 of file Signals.hpp.
Referenced by Timer(), and ~Timer().
QueueType LibWheel::Timer::times [private]
Queue of signal delivery times.
Definition at line 201 of file Signals.hpp.
Referenced by LibWheel::Timer::Handler::operator()().
The documentation for this class was generated from the following files:
Signals.hpp
Signals.cpp