Network Rerouter Daemon (nerd): logmsg.c File Reference
logmsg.c File Reference
#include <syslog.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <time.h>
#include "logmsg.h"
Classes
struct logmsg_t
Internal logmsg configuration object.
Defines
#define _POSIX_SOURCE
#define _BSD_SOURCE
Functions
int logmsg_open (logmsg_target_t target, unsigned options, const char *name)
Initializes the logmsg facility.
int logmsg (logmsg_priority_t priority, const char *format,...)
Prints a message to the current target.
int vlogmsg (logmsg_priority_t priority, const char *format, va_list args)
Prints a message to the current target.
int logmsg_close ()
Shuts down the logmsg facility.
Variables
static const char * _priority_tag []
String table for logmsg priorities (.
static const int _priority_id []
syslog macros corresponding to values of logmsg_priority_t
static logmsg_t _log_config = {logmsg_stderr, 0, "", NULL}
Global logmsg configuration object.
Detailed Description
Author:
Rennie deGraaf
Date:
2007/05/29
Implementation of logmsg - a generic framework for logging error or status messages to various targets. Currently, valid targets are stdout, stderr, syslog, or any file. The default target is stderr. Messages are formatted along syslog conventions.
Todo:
Verify thread safety.
Extend logmsg to allow multiple separate loggers to be used simultaneously, along the lines of Java's "Logger" class.
Definition in file logmsg.c.
Define Documentation
#define _BSD_SOURCE
Definition at line 49 of file logmsg.c.
#define _POSIX_SOURCE
Definition at line 48 of file logmsg.c.
Function Documentation
int logmsg (logmsg_priority_t priority, const char * format, ...)
Prints a message to the current target.
The message is formatted according to syslog() conventions.
Parameters:
priority The message priority. How this is interpreted depends on the target:
logmsg_syslog: Use the equivalent syslog priority.
logmsg_file, logmsg_stdout, logmsg_stderr: Prepend a string to the message indicating the priority
format A printf()-style format string, followed by arguments.
Returns:
0 on success, or -1 on failure
Definition at line 153 of file logmsg.c.
References vlogmsg().
int logmsg_close ()
Shuts down the logmsg facility.
Closes the target appropriately.
Returns:
0 on success, or EOF on failure, with errno set appropriately.
Definition at line 244 of file logmsg.c.
References logmsg_t::target, logmsg_stdout, logmsg_stderr, logmsg_syslog, logmsg_file, and logmsg_t::file.
Referenced by LibWheel::Logmsg::open(), and LibWheel::Logmsg::close().
int logmsg_open (logmsg_target_t target, unsigned options, const char * name)
Initializes the logmsg facility.
Opens and initializes a target, and sets logmsg options.
Parameters:
target The type of target to use.
options A bitfield of option flags.
name A string whose purpose is determined by the value of target:
logmsg_file: The name of the file to use.
logmsg_syslog, logmsg_stdout, logmsg_stderr: A string to prepend to each log message.
Returns:
0 on success or -1 on failure, with errno set appropriately.
Definition at line 110 of file logmsg.c.
References logmsg_t::target, logmsg_t::options, logmsg_t::name, logmsg_t::file, logmsg_stdout, logmsg_stderr, logmsg_syslog, LOGMSG_PID, and logmsg_file.
Referenced by LibWheel::Logmsg::open().
int vlogmsg (logmsg_priority_t priority, const char * format, va_list args)
Prints a message to the current target.
The message is formatted according to syslog() conventions.
Parameters:
priority The message priority. How this is interpreted depends on the target:
logmsg_syslog: Use the equivalent syslog priority.
logmsg_file, logmsg_stdout, logmsg_stderr: Prepend a string to the message indicating the priority
format A printf()-style format string.
args Arguments to format.
Returns:
0 on success, or -1 on failure
Definition at line 178 of file logmsg.c.
References logmsg_t::file, logmsg_t::target, logmsg_stdout, logmsg_stderr, logmsg_file, logmsg_t::name, logmsg_t::options, LOGMSG_PID, _priority_tag, logmsg_syslog, and _priority_id.
Referenced by logmsg(), and LibWheel::Logmsg::operator()().
Variable Documentation
logmsg_t _log_config = {logmsg_stderr, 0, "", NULL} [static]
Global logmsg configuration object.
Definition at line 96 of file logmsg.c.
const int _priority_id[] [static]
Initial value:
{
    LOG_EMERG,
    LOG_ALERT,
    LOG_CRIT,
    LOG_ERR,
    LOG_WARNING,
    LOG_NOTICE,
    LOG_INFO,
    LOG_DEBUG
}
syslog macros corresponding to values of logmsg_priority_t
Definition at line 83 of file logmsg.c.
Referenced by vlogmsg().
const char* _priority_tag[] [static]
Initial value:
{
    "Emergency:",
    "Alert:",
    "Critical:",
    "Error:",
    "Warning:",
    "Notice:",
    "Info:",
    "Debug:"
}
String table for logmsg priorities (.
See also:
logmsg_priority_t).
Definition at line 70 of file logmsg.c.
Referenced by vlogmsg().