Network Rerouter Daemon (nerd): logmsg.h File Reference
logmsg.h File Reference
#include <errno.h>
#include <string.h>
#include <stdarg.h>
Defines
#define LOGMSG_STRERROR strerror
#define LOGMSG_VA_LIST va_list
#define LOGMSG_PID 1
logmsg option: include the PID in logged messages.
#define LOGMSG_LIB(FUNC) logmsg(logmsg_err, "%s: %s (%s:%i)", #FUNC, LOGMSG_STRERROR(errno), __FILE__, __LINE__)
Shortcut to log standard library function errors.
#define LOGMSG_FATAL_EXIT() logmsg(logmsg_notice, "Exiting due to fatal error")
Shortcut to log a fatal exit message.
Enumerations
enum logmsg_target_t { logmsg_stderr, logmsg_stdout, logmsg_syslog, logmsg_file }
Available logging targets.
enum logmsg_priority_t {
logmsg_emerg, logmsg_alert, logmsg_crit, logmsg_err,
logmsg_warning, logmsg_notice, logmsg_info, logmsg_debug
}
Valid logging priorities, from highest to lowest.
Functions
int logmsg_open (logmsg_target_t target, unsigned options, const char *name)
Initializes the logmsg facility.
int logmsg (logmsg_priority_t priority, const char *format,...)
Prints a message to the current target.
int vlogmsg (logmsg_priority_t priority, const char *format, LOGMSG_VA_LIST args)
int logmsg_close ()
Shuts down the logmsg facility.
Detailed Description
Author:
Rennie deGraaf
Date:
2007/05/29
Declarations for the C interface to logmsg - a generic framework for logging error or status messages to various targets.
Definition in file logmsg.h.
Define Documentation
#define LOGMSG_FATAL_EXIT () logmsg(logmsg_notice, "Exiting due to fatal error")
Shortcut to log a fatal exit message.
Definition at line 100 of file logmsg.h.
Referenced by drop_priv(), spc_sanitize_environment(), and spc_sanitize_files().
#define LOGMSG_LIB (FUNC) logmsg(logmsg_err, "%s: %s (%s:%i)", #FUNC, LOGMSG_STRERROR(errno), __FILE__, __LINE__)
Shortcut to log standard library function errors.
Parameters:
FUNC The name of the library function that experienced the error
Definition at line 97 of file logmsg.h.
Referenced by drop_priv(), and spc_sanitize_environment().
#define LOGMSG_PID 1
logmsg option: include the PID in logged messages.
Definition at line 80 of file logmsg.h.
Referenced by logmsg_open(), and vlogmsg().
#define LOGMSG_STRERROR strerror
Definition at line 47 of file logmsg.h.
#define LOGMSG_VA_LIST va_list
Definition at line 48 of file logmsg.h.
Enumeration Type Documentation
enum logmsg_priority_t
Valid logging priorities, from highest to lowest.
Based on syslog priorities.
Enumerator:
logmsg_emerg
The system is unusable.
logmsg_alert
Action must be taken immediately.
logmsg_crit
Critical error condition.
logmsg_err
Error condtion.
logmsg_warning
Warning condition.
logmsg_notice
Normal, but significant, condition.
logmsg_info
Informational message.
logmsg_debug
Debug message.
Definition at line 67 of file logmsg.h.
enum logmsg_target_t
Available logging targets.
Enumerator:
logmsg_stderr
Write messages to stderr (default).
logmsg_stdout
Write messages to stdout.
logmsg_syslog
Send message to syslog.
logmsg_file
Append messages to a file.
Definition at line 57 of file logmsg.h.
Function Documentation
int logmsg (logmsg_priority_t priority, const char * format, ...)
Prints a message to the current target.
The message is formatted according to syslog() conventions.
Parameters:
priority The message priority. How this is interpreted depends on the target:
logmsg_syslog: Use the equivalent syslog priority.
logmsg_file, logmsg_stdout, logmsg_stderr: Prepend a string to the message indicating the priority
format A printf()-style format string, followed by arguments.
Returns:
0 on success, or -1 on failure
Definition at line 153 of file logmsg.c.
References vlogmsg().
int logmsg_close ()
Shuts down the logmsg facility.
Closes the target appropriately.
Returns:
0 on success, or EOF on failure, with errno set appropriately.
Definition at line 244 of file logmsg.c.
References logmsg_t::target, logmsg_stdout, logmsg_stderr, logmsg_syslog, logmsg_file, and logmsg_t::file.
Referenced by LibWheel::Logmsg::open(), and LibWheel::Logmsg::close().
int logmsg_open (logmsg_target_t target, unsigned options, const char * name)
Initializes the logmsg facility.
Opens and initializes a target, and sets logmsg options.
Parameters:
target The type of target to use.
options A bitfield of option flags.
name A string whose purpose is determined by the value of target:
logmsg_file: The name of the file to use.
logmsg_syslog, logmsg_stdout, logmsg_stderr: A string to prepend to each log message.
Returns:
0 on success or -1 on failure, with errno set appropriately.
Definition at line 110 of file logmsg.c.
References logmsg_t::target, logmsg_t::options, logmsg_t::name, logmsg_t::file, logmsg_stdout, logmsg_stderr, logmsg_syslog, LOGMSG_PID, and logmsg_file.
Referenced by LibWheel::Logmsg::open().
int vlogmsg (logmsg_priority_t priority, const char * format, LOGMSG_VA_LIST args)