Network Rerouter Daemon (nerd): LibWheel Namespace Reference
LibWheel Namespace Reference
A set of reusuable software components written in various languages.
Classes
class auto_array
A simple smart pointer for arrays that provides strict ownership semantics in the manner of std::auto_ptr.
class DNSFailure
Exception thrown when a DNS lookup fails.
class DNSError
Exception thrown when an error is encountered parsing a DNS record.
class Logmsg
A C++ front-end to logmsg: a generic framework for logging error or status messages to various targets.
class SignalException
Base class for exceptions thrown by signal handlers.
class Interrupt
Exception to be thrown in response to a SIGINT.
class Thrower
Template for functors to throw exceptions in response to signals.
class SignalQueue
A system for synchronously handling asynchronous signals in a uni-threaded process.
class Timer
Singleton class to manage real time timer interrupts.
class IOException
Exception thrown when an I/O error occurs.
class SocketException
Exception thrown when a socket error occurs.
class ParseError
Exception throws when a parsing error occurs.
class WaitList
A list from which items will be removed after a timeout.
Functions
const std::vector< std::string > getDnsTxt (in_addr_t addr) throw (DNSFailure, DNSError)
Retrieve a DNS TXT record for an IP address.
int uninterruptible_close (int fd)
Close a file descriptor.
ssize_t uninterruptible_read (int fd, unsigned char *buf, size_t count)
Read data from a file descriptor.
std::string ipv4_to_string (in_addr_t a)
Converts an IPv4 address to a string in dotted-decimal format.
int open_files ()
Counts the number of currently-open file descriptors.
void close_files_on_exec (int maxfd)
Set the "close-on-exec" attribute on open file descriptors greater than maxfd.
void write_pid (const char *file)
Write the current PID to a file.
template<typename T , std::size_t N>
static std::size_t arraySize (T(&)[N])
Determines the size of an array, in elements.
Variables
static Logmsg & logmsg = Logmsg::getLogmsg()
Global logmsg object.
Detailed Description
A set of reusuable software components written in various languages.
Function Documentation
template<typename T , std::size_t N> static std::size_t LibWheel::arraySize (T(&) [N]) [inline, static]
Determines the size of an array, in elements.
Parameters:
_ A reference to an array.
Returns:
The number of elements in the array
Note:
This only words for arrays, not pointers.
Definition at line 41 of file util.hpp.
Referenced by IPQ::IpqSocket::setCopyMode(), and IPQ::IpqSocket::sendResponse().
void LibWheel::close_files_on_exec (int maxfd)
Set the "close-on-exec" attribute on open file descriptors greater than maxfd.
Parameters:
maxfd The highest-numbered file descriptor to preserve.
Side Effects:
Logs a message to logmsg on error.
Definition at line 93 of file util.cpp.
References logmsg, and logmsg_err.
Referenced by NERD::ConnectionServer::createConnection().
const std::vector< std::string > LibWheel::getDnsTxt (in_addr_t addr) throw (DNSFailure, DNSError)
Retrieve a DNS TXT record for an IP address.
Parameters:
addr The address to search, in host byte order.
Returns:
The TXT records for addr
Exceptions:
DNSFailure If no TXT record for addr could be found.
DNSError If the DNS TXT record for addr could not be parsed.
Definition at line 59 of file dns.cpp.
References ipv4_to_string().
Referenced by NERD::ConnectionServer::findServer().
std::string LibWheel::ipv4_to_string (in_addr_t a)
Converts an IPv4 address to a string in dotted-decimal format.
Parameters:
a The address to convert, in host byte order
Returns:
The address in dotted-decimal format.
Note:
This is essentially a thread-safe version of inet_ntoa(), except that it takes the address to convert in host byte order.
Definition at line 37 of file util.cpp.
Referenced by getDnsTxt(), IPQ::IpqIpPacket::print(), NERD::ConnectionServer::ServerWritebackHandler::operator()(), NERD::ConnectionServer::handlePacket(), NERD::ConnectionServer::createConnection(), and NERD::ConnectionServer::findServer().
int LibWheel::open_files ()
Counts the number of currently-open file descriptors.
Returns:
The number of open file descriptors, or -1 on error (with errno set appropriately).
Note:
This function assumes that getdtablesize() always works. This may not be true on all systems.
Definition at line 64 of file util.cpp.
Referenced by NERD::ConnectionServer::printStats().
int LibWheel::uninterruptible_close (int fd)
Close a file descriptor.
This function is identical to close(), except that it will resume if interrupted by a signal and will never set EINTR on error.
Parameters:
fd The file descriptor to close.
Returns:
0 on success, or -1 on error (with errno set appropriately).
Definition at line 501 of file Signals.cpp.
Referenced by NERD::ConnectionServer::createConnection().
ssize_t LibWheel::uninterruptible_read (int fd, unsigned char * buf, size_t count)
Read data from a file descriptor.
This function is identical to read(), except that it will resume if interrupted by a signal and will never set EINTR on error. Also, it assumes that fd is in non-blocking mode, and will return -1 and set errno to EAGAIN if no data is available. See the man page for read() for further details.
Parameters:
fd The file descriptor from which to read.
buf The buffer to which to write.
count The maximum number of bytes to read.
Returns:
The number of bytes read, or -1 on error (with errno set appropriately).
Definition at line 525 of file Signals.cpp.
Referenced by NERD::ConnectionServer::ServerWritebackHandler::operator()().
void LibWheel::write_pid (const char * file)
Write the current PID to a file.
Parameters:
file The file to which the PID is to be written.
Note:
Logs messages to LibWheel::logmsg on failure.
Warning:
If file exists, its contents will be truncated.
Definition at line 116 of file util.cpp.
References logmsg, and logmsg_err.
Referenced by main().
Variable Documentation
Logmsg& LibWheel::logmsg = Logmsg::getLogmsg() [static]
Global logmsg object.
Used to emulate the C API in C++.
Definition at line 47 of file Logmsg.hpp.
Referenced by drop_priv(), NERD::ConnectionServer::~ConnectionServer(), NERD::ConnectionServer::operator()(), NERD::ConnectionServer::printStats(), NERD::ConnectionServer::ServerExitHandler::operator()(), NERD::ConnectionServer::ServerWritebackHandler::operator()(), NERD::ConnectionServer::handlePacket(), NERD::ConnectionServer::createConnection(), NERD::ConnectionServer::findServer(), NERD::ConnectionServer::isExecutable(), main(), spc_sanitize_environment(), spc_sanitize_files(), close_files_on_exec(), and write_pid().