Network Rerouter Daemon (nerd): NERD Namespace Reference
NERD Namespace Reference
Functions and classes specific to the Network Rerouter Daemon (nerd).
Classes
class DnsServerRecord
Holds a DNS TXT server record.
class ConnectionServer
The main class for the Network Rerouter Daemon (nerd).
class StatPrinter
Functor to print current server statistics.
Functions
static void print_version ()
Print version info to stderr.
static void print_help (const char *progname)
Print a help message to stderr.
static void parse_args (int argc, char **argv, bool &daemon, bool &verbose)
Parse command-line arguments.
Detailed Description
Functions and classes specific to the Network Rerouter Daemon (nerd).
Function Documentation
static void NERD::parse_args (int argc, char ** argv, bool & daemon, bool & verbose) [static]
Parse command-line arguments.
See the documentation for main() for details.
Parameters:
argc The number of command-line arguments.
argv A null-terminated array of command-line arguments
[out] daemon Set to true on return to run in daemon mode, or false to run in console mode.
[out] verbose Set to true on return to enable verbose logging; false for normal logging.
Definition at line 1433 of file nerd.cpp.
References print_version(), and print_help().
Referenced by main().
static void NERD::print_help (const char * progname) [static]
Print a help message to stderr.
Definition at line 1412 of file nerd.cpp.
Referenced by parse_args().
static void NERD::print_version () [static]
Print version info to stderr.
Definition at line 1397 of file nerd.cpp.
References NERD_VERSION.
Referenced by parse_args().