Network Rerouter Daemon (nerd): IPQ Namespace Reference
IPQ Namespace Reference
A C++ interface to libipq, the old iptables userspace-queueing system.
Classes
class IpqException
Base class for exceptions thrown by IPQ methods.
class IpqSocket
A program's link to libipq.
class IpqPacket
Base class for packets received via IpqSocket.
class IpqIpPacket
A complete IPv4 packet received via IpqSocket.
class IpqTcpPacket
An complete IPv4/TCP packet that was received via IpqSocket.
class IpqUdpPacket
An complete IPv4/UDP packet that was received via IpqSocket.
Functions
boost::uint16_t ip_checksum (boost::uint32_t init, boost::uint8_t *buf, std::size_t len)
Compute an IP checksum (as described in RFC 791).
Detailed Description
A C++ interface to libipq, the old iptables userspace-queueing system.
Function Documentation
boost::uint16_t IPQ::ip_checksum (boost::uint32_t init, boost::uint8_t * buf, std::size_t len)
Compute an IP checksum (as described in RFC 791).
This implementation was adapted from RFC 1071.
Parameters:
init The sum of previously-summed data. Use this for computing TCP checksums; normally, this can be set to 0.
buf The buffer to check.
len The size of buffer, in bytes.
Definition at line 58 of file IPQ.cpp.
Referenced by IPQ::IpqIpPacket::updateChecksums(), IPQ::IpqTcpPacket::updateChecksums(), and IPQ::IpqUdpPacket::updateChecksums().