Network Rerouter Daemon (nerd): nerd.cpp File Reference
nerd.cpp File Reference
#include <stdexcept>
#include <iostream>
#include <string>
#include <cstdlib>
#include <ctime>
#include <ext/hash_map>
#include <boost/cstdint.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/shared_ptr.hpp>
#include <unistd.h>
#include <fcntl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <sys/time.h>
#include <sys/resource.h>
#include <getopt.h>
#include <arpa/inet.h>
#include <netinet/ip.h>
#include <netinet/tcp.h>
#include "Logmsg.hpp"
#include "Signals.hpp"
#include "IPQ.hpp"
#include "WaitList.hpp"
#include "util.hpp"
#include "spc_sanitize.h"
#include "drop_priv.h"
#include "dns.hpp"
#include "DnsServerRecord.hpp"
#include "libwheel.h"
#include "nerd.h"
Classes
class NERD::ConnectionServer
The main class for the Network Rerouter Daemon (nerd).
class NERD::ConnectionServer::UnknownConnectionException
Exception thrown by getRedirectRule() when a packet does not match any existing connection record.
class NERD::ConnectionServer::UnknownServerException
Exception thrown by findServer() when no server program can be found to handle a new connection.
struct NERD::ConnectionServer::AddressPair
The source and destination addresses of IP packets travelling in one direction in a connection.
class NERD::ConnectionServer::AddressPairHash
A functor that computes a hash of an AddressPair, suitable for use with __gnu_cxx::hash_map.
class NERD::ConnectionServer::Connection
A description of a connection managed by a server program.
struct NERD::ConnectionServer::PendingConnection
Information pertaining to a server that is starting up to handle a connection.
struct NERD::ConnectionServer::ServerRecord
Information about a server program to be started.
class NERD::ConnectionServer::ServerExitHandler
Functor to handle SIGCHLD signals received through LibWheel::SignalQueue.
class NERD::ConnectionServer::ServerWritebackHandler
Functor to handle SIGIO signals received through LibWheel::SignalQueue.
class NERD::StatPrinter
Functor to print current server statistics.
Namespaces
namespace NERD
Functions and classes specific to the Network Rerouter Daemon (nerd).
namespace LibWheel
A set of reusuable software components written in various languages.
Defines
#define LOCALHOST_IP 0x7f000001
127.0.0.1, as an integer in HBO.
#define MAGIC_PORT 1
To servers, client connections will appear to come from this port on localhost.
#define PIDFILE "/var/run/nerd.pid"
When in daemon mode, write the PID to this file.
Functions
static void NERD::print_version ()
Print version info to stderr.
static void NERD::print_help (const char *progname)
Print a help message to stderr.
static void NERD::parse_args (int argc, char **argv, bool &daemon, bool &verbose)
Parse command-line arguments.
int main (int argc, char *argv[])
Entry point for the Network Rerouter Daemon (nerd).
Detailed Description
Author:
Rennie deGraaf
Date:
2007/12/13
Main module for the Network Rerouter Daemon (nerd).
Definition in file nerd.cpp.
Define Documentation
#define LOCALHOST_IP 0x7f000001
127.0.0.1, as an integer in HBO.
Definition at line 48 of file nerd.cpp.
Referenced by NERD::ConnectionServer::ConnectionServer(), NERD::ConnectionServer::ServerWritebackHandler::operator()(), and NERD::ConnectionServer::handlePacket().
#define MAGIC_PORT 1
To servers, client connections will appear to come from this port on localhost.
Definition at line 49 of file nerd.cpp.
Referenced by NERD::ConnectionServer::ConnectionServer(), and NERD::ConnectionServer::ServerWritebackHandler::operator()().
#define PIDFILE "/var/run/nerd.pid"
When in daemon mode, write the PID to this file.
Definition at line 50 of file nerd.cpp.
Referenced by main().
Function Documentation
int main (int argc, char * argv[])
Entry point for the Network Rerouter Daemon (nerd).
The following command-line arguments are accepted:
-D (--daemon) Detach from the console and run as a daemon.
-V (--verbose) Log extra status messages.
-h (--help) Print a help message and exit.
-v (--version) Print a version message and exit.
By default, status and error messages are logged to stderr; in daemon mode, they are sent to syslog. In debug builds (in which the macro DEBUG is defined), verbose logging is automatically enabled and daemon mode is disabled.
The following signals can be sent to the program:
SIGINT (^C) Stop processing packets, clean up and exit normally.
SIGUSR1 Print status information to the log device (stderr in console mode, or syslog in daemon mode).
This program needs root privileges to run. It will log an error message and exit if run as any other user.
Definition at line 1514 of file nerd.cpp.
References LibWheel::logmsg, logmsg_stderr, spc_sanitize_environment(), spc_sanitize_files(), NERD::parse_args(), LibWheel::SignalQueue::setHandler(), LibWheel::SignalQueue::HANDLE, LibWheel::SignalQueue::addHandler(), NERD_SERVER_ROOT, logmsg_syslog, LibWheel::write_pid(), PIDFILE, and logmsg_crit.