Network Rerouter Daemon (nerd): spc_sanitize.c File Reference
spc_sanitize.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <paths.h>
#include <limits.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <errno.h>
#include "logmsg.h"
Defines
#define _POSIX_SOURCE
#define _BSD_SOURCE
#define SIZE_T_MAX (sizeof(size_t))
#define OPEN_MAX 256
Functions
void spc_sanitize_environment (int preservec, const char **preservev)
Sanitizes the system environment.
static int open_devnull (int fd)
Attempts to open /dev/null as stdin, stdout, or stderr.
void spc_sanitize_files (int maxfd)
Closes all file descriptors above a limit, and ensures that stdin, stdout, and stderr are open.
Variables
char ** environ
Pointer to the global environment table.
static const char * spc_restricted_environ []
Default environment configuration.
static const char * spc_preserve_environ []
Environment variables to preserve if present.
Detailed Description
Author:
Rennie deGraaf
Date:
2007/05/27
Functions to sanitize the system environment.
Definition in file spc_sanitize.c.
Define Documentation
#define _BSD_SOURCE
Definition at line 53 of file spc_sanitize.c.
#define _POSIX_SOURCE
Definition at line 52 of file spc_sanitize.c.
#define OPEN_MAX 256
Definition at line 71 of file spc_sanitize.c.
Referenced by spc_sanitize_files().
#define SIZE_T_MAX (sizeof(size_t))
Definition at line 67 of file spc_sanitize.c.
Referenced by spc_sanitize_environment().
Function Documentation
static int open_devnull (int fd) [static]
Attempts to open /dev/null as stdin, stdout, or stderr.
Parameters:
fd The stream to open. Must be 0 for stdin, 1 for stdout, or 2 for stderr.
Returns:
Non-zero on success, or zero on failure.
Definition at line 217 of file spc_sanitize.c.
Referenced by spc_sanitize_files().
void spc_sanitize_environment (int preservec, const char ** preservev)
Sanitizes the system environment.
Sets all variables in spc_restricted_environ to default values and deletes all other variables not listed either in preservev or spc_preserve_environ.
Parameters:
preservec The number of variables in preservev.
preservev A list of environemnt variable names to preserve.
Note:
Logs an error message to the logmsg facility and calls abort() on integer overflow or memory allocation failure. Changes the value of the global variable environ.
Warning:
This function will leak memory if called more than once.
Definition at line 111 of file spc_sanitize.c.
References spc_restricted_environ, SIZE_T_MAX, LibWheel::logmsg, logmsg_err, LOGMSG_FATAL_EXIT, spc_preserve_environ, LOGMSG_LIB, and environ.
Referenced by main().
void spc_sanitize_files (int maxfd)
Closes all file descriptors above a limit, and ensures that stdin, stdout, and stderr are open.
Parameters:
maxfd The highest-numbered file descriptor to preserve. Set to 2 or less to close all files except for stdin, stdout, and stderr.
Note:
If stdin, stdout, or stderr is closed and cannot be opened, attempts to log a message through the logmsg facility and calls abort().
Definition at line 235 of file spc_sanitize.c.
References OPEN_MAX, open_devnull(), LibWheel::logmsg, logmsg_err, and LOGMSG_FATAL_EXIT.
Referenced by main().
Variable Documentation
char** environ
Pointer to the global environment table.
Referenced by spc_sanitize_environment().
const char* spc_preserve_environ[] [static]
Initial value:
{
    "TZ",
    NULL
}
Environment variables to preserve if present.
Definition at line 93 of file spc_sanitize.c.
Referenced by spc_sanitize_environment().
const char* spc_restricted_environ[] [static]
Initial value:
{
    "IFS= \t\n",
    "PATH=" _PATH_STDPATH,
    NULL
}
Default environment configuration.
Definition at line 83 of file spc_sanitize.c.
Referenced by spc_sanitize_environment().